<template>
    <div class="report-break">
        <h1 class="q-my-lg">Introduction</h1>
        <p>
            Thank you for generating a report using the BC Water Tool! In this
            report, you’ll find a detailed water resource evaluation for the
            watershed you selected. Naturally, the information in the report is
            contextual; based on the stream, river or lake you selected, the
            report describes:
        </p>
        <ul>
            <li>The quantity and timing of water flow;</li>
            <li>Existing water allocations;</li>
            <li>
                The needs of the environment, and sustainable withdrawal
                thresholds; and
            </li>
            <li>
                Other characteristics of the watershed, such as landcover,
                climate, and topography.
            </li>
        </ul>
        <p>
            Some of the information presented in this report was generated by
            hydrology models using large data sets of streamflow measurements,
            and physical and environmental characteristics. In general, this
            report estimates what the average conditions are like – not
            necessarily what may be happening at this moment or this year in
            particular.
        </p>
        <p>
            As you read through the material, if you find yourself wanting to
            know more, all of the details regarding our methods, data sources,
            and the performance of the BC Water Tool are provided at the end of
            the report, along with contact information to reach government
            departments with any questions about water rights or water
            management in BC<NoteLink :note-number="1" />.
        </p>
        <p>I hope that you find the information very useful.</p>
        <hr class="q-my-xl" />
    </div>
</template>

<script setup>
import NoteLink from "@/components/watershed/report/NoteLink.vue";
</script>
