version: '3.9'
services:

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
      args:
        VITE_BASE_API_URL: 'http://localhost:8000'
    ports:
      - "5173:8081"
    depends_on:
      backend:
        condition: service_started
  backend:
    build: './backend'
    ports:
      - "8000:8000"
    environment:
      - FLASK_ENV=development

