apiVersion: v2
name: quickstart-openshift
description: Helm Chart for deploying the Client & Backend of the BC Water Tool Consolidation
icon: https://www.nicepng.com/png/detail/521-5211827_bc-icon-british-columbia-government-logo.png
type: application
version: 0.1.0
appVersion: "1.0.0"
# TODO: Add More Maintainers
maintainers:
  - name: Liam Franke
    email: liam@foundryspatial.com
