apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: airflow-data
  namespace: cdd771-dev
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 15Gi
  storageClassName: netapp-file-standard
  volumeMode: Filesystem
