executor: KubernetesExecutor

extraSecrets:
  airflow-flowworks-credentials:
    type: Opaque
    stringData: |
      BCWAT_FLOWWORKS_PASSWORD: "{{ .Values.secrets.bcwatFlowworks.password }}"
      BCWAT_FLOWWORKS_USERNAME: "{{ .Values.secrets.bcwatFlowworks.username }}"
  airflow-fernet-key:
    type: Opaque
    stringData: |
      fernet-key: "{{ .Values.secrets.fernet.key }}"
  airflow-webserver-secret-key:
    type: Opaque
    stringData: |
      webserver-secret-key: "{{ .Values.secrets.webserver.key }}"
  airflow-database-connection:
    type: Opaque
    stringData: |
      connection: {{ index ((lookup "v1" "Secret" .Release.Namespace "bcwat-test-crunchy-pguser-airflow-metadata-admin").data) "uri" | b64dec | quote }}
  airflow-conn-bcwat-db:
    type: Opaque
    stringData: |
      uri: {{ index ((lookup "v1" "Secret" .Release.Namespace "bcwat-test-crunchy-pguser-bcwat-airflow-read-write").data) "pgbouncer-uri" | b64dec | quote }}
  airflow-sendgrid-default:
    type: Opaque
    stringData: |
      auth: '{
          "conn_type": "sendgrid",
          "password": "{{ .Values.secrets.sendgridApiKey }}"
      }'

fernetKeySecretName: airflow-fernet-key
webserverSecretKeySecretName: airflow-webserver-secret-key

data:
  metadataSecretName: airflow-database-connection
  resultBackendSecretName: airflow-database-connection

logs:
  persistence:
    enabled: true
    storageClassName: netapp-file-standard
    size: 8Gi

airflowVersion: "2.10.5"

images:
  airflow:
    repository: ghcr.io/bcgov/nr-bcwat/airflow
    tag: latest
    pullPolicy: Always

webserver:
  env:
    - name: AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION
      value: "False"
  extraInitContainers:
    - name: flyway-migrations
      image: "ghcr.io/bcgov/nr-bcwat/migrations:{{ .Values.images.airflow.tag }}"
      imagePullPolicy: Always
      env:
        - name: FLYWAY_URL
          valueFrom:
            secretKeyRef:
              name: "{{ .Values.migrations.databaseAlias }}-pguser-{{ .Values.migrations.databaseUser }}"
              key: jdbc-uri
        - name: FLYWAY_USER
          valueFrom:
            secretKeyRef:
              name: "{{ .Values.migrations.databaseAlias }}-pguser-{{ .Values.migrations.databaseUser }}"
              key: user
        - name: FLYWAY_PASSWORD
          valueFrom:
            secretKeyRef:
              name: "{{ .Values.migrations.databaseAlias }}-pguser-{{ .Values.migrations.databaseUser }}"
              key: password
        - name: FLYWAY_BASELINE_ON_MIGRATE
          value: "true"
        - name: FLYWAY_DEFAULT_SCHEMA
          value: "USERS"
        - name: FLYWAY_CONNECT_RETRIES
          value: "10"
        - name: FLYWAY_GROUP
          value: "true"
      resources:
        requests:
          cpu: 50m
          memory: 75Mi
  waitForMigrations:
    enabled: false
  securityContext:
    runAsUser: 1017950000
    fsGroup: 1017950000      # a value within the allowed fsGroup range (1017950000/10000)

scheduler:
  env:
    - name: AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION
      value: "False"
  waitForMigrations:
    enabled: false
  securityContext:
    runAsUser: 1017950000
    fsGroup: 1017950000      # a value within the allowed fsGroup range (1017950000/10000)

migrateDatabaseJob:
  env:
    - name: AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION
      value: "False"
  securityContext:
    runAsUser: 1017950000
    fsGroup: 1017950000      # a value within the allowed fsGroup range (1017950000/10000)
  ttlSecondsAfterFinished: 180

createUserJob:
  env:
    - name: AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION
      value: "False"
  securityContext:
    runAsUser: 1017950000
    fsGroup: 1017950000      # a value within the allowed fsGroup range (1017950000/10000)
  ttlSecondsAfterFinished: 180

triggerer:
  env:
    - name: AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION
      value: "False"
  persistence:
    enabled: false
  waitForMigrations:
    enabled: false
  securityContext:
    runAsUser: 1017950000
    fsGroup: 1017950000      # a value within the allowed fsGroup range (1017950000/10000)

redis:
  enabled: false

postgresql:
  enabled: false

flower:
  enabled: false

statsd:
  enabled: false

dags:
  persistence:
    enabled: false

