executor: KubernetesExecutor

config:
  core:
    min_serialized_dag_update_interval: 300
    min_serialized_dag_fetch_interval: 60
  dag_processor:
    min_file_process_interval: 300
    refresh_interval: 3600

extraSecrets:
  airflow-flowworks-credentials:
    type: Opaque
    stringData: |
      BCWAT_FLOWWORKS_PASSWORD: "{{ .Values.secrets.bcwatFlowworks.password }}"
      BCWAT_FLOWWORKS_USERNAME: "{{ .Values.secrets.bcwatFlowworks.username }}"
  airflow-fernet-key:
    type: Opaque
    stringData: |
      fernet-key: "{{ .Values.secrets.fernet.key }}"
  airflow-api-secret-key:
    type: Opaque
    stringData: |
      api-secret-key: "{{ .Values.secrets.api.secretKey }}"
  airflow-jwt-secret:
    type: Opaque
    stringData: |
      jwt-secret: "{{ .Values.secrets.api.jwtKey }}"
  airflow-migrate-db-conn:
    type: Opaque
    stringData: |
      connection: {{ index ((lookup "v1" "Secret" .Release.Namespace "bcwat-prod-crunchy-pguser-airflow-metadata-admin").data) "uri" | b64dec | quote }}
  airflow-rw-db-conn:
    type: Opaque
    stringData: |
      connection: {{ index ((lookup "v1" "Secret" .Release.Namespace "bcwat-prod-crunchy-pguser-airflow-metadata-rw").data) "pgbouncer-uri" | b64dec | quote }}
  bcwat-airflow-rw-db-conn:
    type: Opaque
    stringData: |
      connection: {{ index ((lookup "v1" "Secret" .Release.Namespace "bcwat-prod-crunchy-pguser-bcwat-airflow-read-write").data) "pgbouncer-uri" | b64dec | quote }}
  airflow-sendgrid-default:
    type: Opaque
    stringData: |
      auth: '{
          "conn_type": "sendgrid",
          "password": "{{ .Values.secrets.sendgridApiKey }}"
      }'

fernetKeySecretName: airflow-fernet-key
apiSecretKeySecretName: airflow-api-secret-key
jwtSecretName: airflow-jwt-secret

data:
  metadataSecretName: airflow-rw-db-conn

logs:
  persistence:
    enabled: true
    storageClassName: netapp-file-standard
    size: 8Gi

airflowVersion: "3.1.7"

images:
  airflow:
    repository: ghcr.io/bcgov/nr-bcwat/airflow
    tag: latest
    pullPolicy: Always

securityContext:
  runAsUser: 1017940000
  fsGroup: 1017940000      # a value within the allowed fsGroup range (1017940000/10000)

apiServer:
  startupProbe:
    timeoutSeconds: 60
  env:
    - name: AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION
      value: "False"
    - name: ENVIRONMENT
      value: PRODUCTION
    - name: AIRFLOW__EXECUTION_API__JWT_EXPIRATION_TIME
      value: "21600"
    - name: AIRFLOW__API_AUTH__JWT_LEEWAY
      value: "60"
  resources:
    limits:
      memory: 2G
    requests:
      memory: 2G
  extraInitContainers:
    - name: flyway-migrations
      image: "ghcr.io/bcgov/nr-bcwat/migrations:{{ .Values.images.airflow.tag }}"
      imagePullPolicy: Always
      env:
        - name: FLYWAY_URL
          valueFrom:
            secretKeyRef:
              name: "~"
              key: jdbc-uri
        - name: FLYWAY_USER
          valueFrom:
            secretKeyRef:
              name: "~"
              key: user
        - name: FLYWAY_PASSWORD
          valueFrom:
            secretKeyRef:
              name: "~"
              key: password
        - name: FLYWAY_BASELINE_ON_MIGRATE
          value: "true"
        - name: FLYWAY_DEFAULT_SCHEMA
          value: "USERS"
        - name: FLYWAY_CONNECT_RETRIES
          value: "10"
        - name: FLYWAY_GROUP
          value: "true"
      resources:
        requests:
          memory: 1G
        limits:
          memory: 1G
  waitForMigrations:
    enabled: true

scheduler:
  env:
    - name: AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION
      value: "False"
    - name: ENVIRONMENT
      value: PRODUCTION
    - name: AIRFLOW__EXECUTION_API__JWT_EXPIRATION_TIME
      value: "21600"
    - name: AIRFLOW__API_AUTH__JWT_LEEWAY
      value: "60"
  resources:
    limits:
      memory: 2G
    requests:
      memory: 2G
  waitForMigrations:
    enabled: true

migrateDatabaseJob:
  env:
    - name: AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION
      value: "False"
    - name: AIRFLOW__CORE__SQL_ALCHEMY_CONN
      valueFrom:
        secretKeyRef:
          name: airflow-migrate-db-conn
          key: connection
    - name: AIRFLOW__DATABASE__SQL_ALCHEMY_CONN
      valueFrom:
        secretKeyRef:
          name: airflow-migrate-db-conn
          key: connection
    - name: AIRFLOW_CONN_AIRFLOW_DB
      valueFrom:
        secretKeyRef:
          name: airflow-migrate-db-conn
          key: connection
  resources:
    requests:
      memory: 1G
    limits:
      memory: 1G
  ttlSecondsAfterFinished: 180

createUserJob:
  env:
    - name: AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION
      value: "False"
    - name: AIRFLOW__CORE__SQL_ALCHEMY_CONN
      valueFrom:
        secretKeyRef:
          name: airflow-migrate-db-conn
          key: connection
    - name: AIRFLOW__DATABASE__SQL_ALCHEMY_CONN
      valueFrom:
        secretKeyRef:
          name: airflow-migrate-db-conn
          key: connection
    - name: AIRFLOW_CONN_AIRFLOW_DB
      valueFrom:
        secretKeyRef:
          name: airflow-migrate-db-conn
          key: connection
  resources:
    requests:
      memory: 1G
    limits:
      memory: 1G
  ttlSecondsAfterFinished: 180

redis:
  enabled: false

triggerer:
  env:
    - name: AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION
      value: "False"
    - name: ENVIRONMENT
      value: PRODUCTION
    - name: AIRFLOW__EXECUTION_API__JWT_EXPIRATION_TIME
      value: "21600"
    - name: AIRFLOW__API_AUTH__JWT_LEEWAY
      value: "60"
  resources:
    limits:
      memory: 1.5G
    requests:
      memory: 1.5G
  persistence:
    enabled: false
  waitForMigrations:
    enabled: true

postgresql:
  enabled: false

flower:
  enabled: false

statsd:
  enabled: false

dags:
  persistence:
    enabled: false
