apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: airflow-file-mount
  namespace: cdd771-prod
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 30Gi
  storageClassName: netapp-file-standard
  volumeMode: Filesystem
