bcwat_ws_query = '''

    CREATE SCHEMA "bcwat_ws";

    -- TABLE CREATION --

    CREATE TABLE "bcwat_ws"."fwa_fund" (
    "watershed_feature_id" integer PRIMARY KEY,
    "fwa_watershed_code" text DEFAULT '',
    "local_watershed_code" text DEFAULT '',
    "the_geom" geometry(MultiPolygon, 3005),
    "centroid" geometry(Point, 3005),
    "lake_name" text DEFAULT '',
    "report" smallint,
    "local_watershed_order" integer,
    "has_upstream" boolean DEFAULT false,
    "in_study_area" boolean NOT NULL DEFAULT false,
    "point_inside_poly" geometry(Point,3005),
    "lake" boolean DEFAULT false,
    "area" DOUBLE PRECISION,
    "geom4326" geometry(MultiPolygon,4326),
    "point_inside_poly4326" geometry(Point, 4326),
    "pip_x" DOUBLE PRECISION,
    "pip_y" DOUBLE PRECISION,
    "watershed_feature_id_foundry_eca" integer,
    "has_netcdf" boolean DEFAULT false
    );

    CREATE TABLE "bcwat_ws"."fwa_union" (
    "fwa_watershed_code" text PRIMARY KEY,
    "geom_simp4326" geometry(MultiPolygon,4326)
    );

    CREATE TABLE "bcwat_ws"."fund_rollup" (
    "watershed_feature_id" integer PRIMARY KEY,
    "upstream_area" DOUBLE PRECISION NOT NULL,
    "dem400" DOUBLE PRECISION NOT NULL,
    "ppt01" DOUBLE PRECISION NOT NULL,
    "ppt02" DOUBLE PRECISION NOT NULL,
    "ppt03" DOUBLE PRECISION NOT NULL,
    "ppt04" DOUBLE PRECISION NOT NULL,
    "ppt05" DOUBLE PRECISION NOT NULL,
    "ppt06" DOUBLE PRECISION NOT NULL,
    "ppt07" DOUBLE PRECISION NOT NULL,
    "ppt08" DOUBLE PRECISION NOT NULL,
    "ppt09" DOUBLE PRECISION NOT NULL,
    "ppt10" DOUBLE PRECISION NOT NULL,
    "ppt11" DOUBLE PRECISION NOT NULL,
    "ppt12" DOUBLE PRECISION NOT NULL,
    "tave01" DOUBLE PRECISION NOT NULL,
    "tave02" DOUBLE PRECISION NOT NULL,
    "tave03" DOUBLE PRECISION NOT NULL,
    "tave04" DOUBLE PRECISION NOT NULL,
    "tave05" DOUBLE PRECISION NOT NULL,
    "tave06" DOUBLE PRECISION NOT NULL,
    "tave07" DOUBLE PRECISION NOT NULL,
    "tave08" DOUBLE PRECISION NOT NULL,
    "tave09" DOUBLE PRECISION NOT NULL,
    "tave10" DOUBLE PRECISION NOT NULL,
    "tave11" DOUBLE PRECISION NOT NULL,
    "tave12" DOUBLE PRECISION NOT NULL,
    "pas01" DOUBLE PRECISION NOT NULL,
    "pas02" DOUBLE PRECISION NOT NULL,
    "pas03" DOUBLE PRECISION NOT NULL,
    "pas04" DOUBLE PRECISION NOT NULL,
    "pas05" DOUBLE PRECISION NOT NULL,
    "pas06" DOUBLE PRECISION NOT NULL,
    "pas07" DOUBLE PRECISION NOT NULL,
    "pas08" DOUBLE PRECISION NOT NULL,
    "pas09" DOUBLE PRECISION NOT NULL,
    "pas10" DOUBLE PRECISION NOT NULL,
    "pas11" DOUBLE PRECISION NOT NULL,
    "pas12" DOUBLE PRECISION NOT NULL,
    "pas01_a2" DOUBLE PRECISION NOT NULL,
    "pas01_b1" DOUBLE PRECISION NOT NULL,
    "pas01_a1b" DOUBLE PRECISION NOT NULL,
    "pas02_a2" DOUBLE PRECISION NOT NULL,
    "pas02_b1" DOUBLE PRECISION NOT NULL,
    "pas02_a1b" DOUBLE PRECISION NOT NULL,
    "pas03_a2" DOUBLE PRECISION NOT NULL,
    "pas03_b1" DOUBLE PRECISION NOT NULL,
    "pas03_a1b" DOUBLE PRECISION NOT NULL,
    "pas04_a2" DOUBLE PRECISION NOT NULL,
    "pas04_b1" DOUBLE PRECISION NOT NULL,
    "pas04_a1b" DOUBLE PRECISION NOT NULL,
    "pas05_a2" DOUBLE PRECISION NOT NULL,
    "pas05_b1" DOUBLE PRECISION NOT NULL,
    "pas05_a1b" DOUBLE PRECISION NOT NULL,
    "pas06_a2" DOUBLE PRECISION NOT NULL,
    "pas06_b1" DOUBLE PRECISION NOT NULL,
    "pas06_a1b" DOUBLE PRECISION NOT NULL,
    "pas07_a2" DOUBLE PRECISION NOT NULL,
    "pas07_b1" DOUBLE PRECISION NOT NULL,
    "pas07_a1b" DOUBLE PRECISION NOT NULL,
    "pas08_a2" DOUBLE PRECISION NOT NULL,
    "pas08_b1" DOUBLE PRECISION NOT NULL,
    "pas08_a1b" DOUBLE PRECISION NOT NULL,
    "pas09_a2" DOUBLE PRECISION NOT NULL,
    "pas09_b1" DOUBLE PRECISION NOT NULL,
    "pas09_a1b" DOUBLE PRECISION NOT NULL,
    "pas10_a2" DOUBLE PRECISION NOT NULL,
    "pas10_b1" DOUBLE PRECISION NOT NULL,
    "pas10_a1b" DOUBLE PRECISION NOT NULL,
    "pas11_a2" DOUBLE PRECISION NOT NULL,
    "pas11_b1" DOUBLE PRECISION NOT NULL,
    "pas11_a1b" DOUBLE PRECISION NOT NULL,
    "pas12_a2" DOUBLE PRECISION NOT NULL,
    "pas12_b1" DOUBLE PRECISION NOT NULL,
    "pas12_a1b" DOUBLE PRECISION NOT NULL,
    "ppt01_a2" DOUBLE PRECISION NOT NULL,
    "ppt01_b1" DOUBLE PRECISION NOT NULL,
    "ppt01_a1b" DOUBLE PRECISION NOT NULL,
    "ppt02_a2" DOUBLE PRECISION NOT NULL,
    "ppt02_b1" DOUBLE PRECISION NOT NULL,
    "ppt02_a1b" DOUBLE PRECISION NOT NULL,
    "ppt03_a2" DOUBLE PRECISION NOT NULL,
    "ppt03_b1" DOUBLE PRECISION NOT NULL,
    "ppt03_a1b" DOUBLE PRECISION NOT NULL,
    "ppt04_a2" DOUBLE PRECISION NOT NULL,
    "ppt04_b1" DOUBLE PRECISION NOT NULL,
    "ppt04_a1b" DOUBLE PRECISION NOT NULL,
    "ppt05_a2" DOUBLE PRECISION NOT NULL,
    "ppt05_b1" DOUBLE PRECISION NOT NULL,
    "ppt05_a1b" DOUBLE PRECISION NOT NULL,
    "ppt06_a2" DOUBLE PRECISION NOT NULL,
    "ppt06_b1" DOUBLE PRECISION NOT NULL,
    "ppt06_a1b" DOUBLE PRECISION NOT NULL,
    "ppt07_a2" DOUBLE PRECISION NOT NULL,
    "ppt07_b1" DOUBLE PRECISION NOT NULL,
    "ppt07_a1b" DOUBLE PRECISION NOT NULL,
    "ppt08_a2" DOUBLE PRECISION NOT NULL,
    "ppt08_b1" DOUBLE PRECISION NOT NULL,
    "ppt08_a1b" DOUBLE PRECISION NOT NULL,
    "ppt09_a2" DOUBLE PRECISION NOT NULL,
    "ppt09_b1" DOUBLE PRECISION NOT NULL,
    "ppt09_a1b" DOUBLE PRECISION NOT NULL,
    "ppt10_a2" DOUBLE PRECISION NOT NULL,
    "ppt10_b1" DOUBLE PRECISION NOT NULL,
    "ppt10_a1b" DOUBLE PRECISION NOT NULL,
    "ppt11_a2" DOUBLE PRECISION NOT NULL,
    "ppt11_b1" DOUBLE PRECISION NOT NULL,
    "ppt11_a1b" DOUBLE PRECISION NOT NULL,
    "ppt12_a2" DOUBLE PRECISION NOT NULL,
    "ppt12_b1" DOUBLE PRECISION NOT NULL,
    "ppt12_a1b" DOUBLE PRECISION NOT NULL,
    "tave01_a2" DOUBLE PRECISION NOT NULL,
    "tave01_b1" DOUBLE PRECISION NOT NULL,
    "tave01_a1b" DOUBLE PRECISION NOT NULL,
    "tave02_a2" DOUBLE PRECISION NOT NULL,
    "tave02_b1" DOUBLE PRECISION NOT NULL,
    "tave02_a1b" DOUBLE PRECISION NOT NULL,
    "tave03_a2" DOUBLE PRECISION NOT NULL,
    "tave03_b1" DOUBLE PRECISION NOT NULL,
    "tave03_a1b" DOUBLE PRECISION NOT NULL,
    "tave04_a2" DOUBLE PRECISION NOT NULL,
    "tave04_b1" DOUBLE PRECISION NOT NULL,
    "tave04_a1b" DOUBLE PRECISION NOT NULL,
    "tave05_a2" DOUBLE PRECISION NOT NULL,
    "tave05_b1" DOUBLE PRECISION NOT NULL,
    "tave05_a1b" DOUBLE PRECISION NOT NULL,
    "tave06_a2" DOUBLE PRECISION NOT NULL,
    "tave06_b1" DOUBLE PRECISION NOT NULL,
    "tave06_a1b" DOUBLE PRECISION NOT NULL,
    "tave07_a2" DOUBLE PRECISION NOT NULL,
    "tave07_b1" DOUBLE PRECISION NOT NULL,
    "tave07_a1b" DOUBLE PRECISION NOT NULL,
    "tave08_a2" DOUBLE PRECISION NOT NULL,
    "tave08_b1" DOUBLE PRECISION NOT NULL,
    "tave08_a1b" DOUBLE PRECISION NOT NULL,
    "tave09_a2" DOUBLE PRECISION NOT NULL,
    "tave09_b1" DOUBLE PRECISION NOT NULL,
    "tave09_a1b" DOUBLE PRECISION NOT NULL,
    "tave10_a2" DOUBLE PRECISION NOT NULL,
    "tave10_b1" DOUBLE PRECISION NOT NULL,
    "tave10_a1b" DOUBLE PRECISION NOT NULL,
    "tave11_a2" DOUBLE PRECISION NOT NULL,
    "tave11_b1" DOUBLE PRECISION NOT NULL,
    "tave11_a1b" DOUBLE PRECISION NOT NULL,
    "tave12_a2" DOUBLE PRECISION NOT NULL,
    "tave12_b1" DOUBLE PRECISION NOT NULL,
    "tave12_a1b" DOUBLE PRECISION NOT NULL,
    "lcc_shrub" DOUBLE PRECISION NOT NULL,
    "lcc_grassland" DOUBLE PRECISION NOT NULL,
    "lcc_coniferous" DOUBLE PRECISION NOT NULL,
    "lcc_water" DOUBLE PRECISION NOT NULL,
    "lcc_snow" DOUBLE PRECISION NOT NULL,
    "lcc_developed" DOUBLE PRECISION NOT NULL,
    "lcc_wetland" DOUBLE PRECISION NOT NULL,
    "lcc_herb" DOUBLE PRECISION NOT NULL,
    "lcc_deciduous" DOUBLE PRECISION NOT NULL,
    "lcc_mixed" DOUBLE PRECISION NOT NULL,
    "lcc_barren" DOUBLE PRECISION NOT NULL,
    "lcc_cropland" DOUBLE PRECISION NOT NULL,
    "q01" DOUBLE PRECISION NOT NULL,
    "q02" DOUBLE PRECISION NOT NULL,
    "q03" DOUBLE PRECISION NOT NULL,
    "q04" DOUBLE PRECISION NOT NULL,
    "q05" DOUBLE PRECISION NOT NULL,
    "q06" DOUBLE PRECISION NOT NULL,
    "q07" DOUBLE PRECISION NOT NULL,
    "q08" DOUBLE PRECISION NOT NULL,
    "q09" DOUBLE PRECISION NOT NULL,
    "q10" DOUBLE PRECISION NOT NULL,
    "q11" DOUBLE PRECISION NOT NULL,
    "q12" DOUBLE PRECISION NOT NULL,
    "qyr" DOUBLE PRECISION NOT NULL,
    "rr" boolean NOT NULL,
    "downstream_id" integer NOT NULL,
    "summer_sensitivity" boolean DEFAULT false,
    "winter_sensitivity" boolean DEFAULT true,
    "elevs" DOUBLE PRECISION[]
    );

    CREATE TABLE "bcwat_ws"."fund_rollup_report" (
    "watershed_feature_id" integer PRIMARY KEY,
    "watershedarea" numeric NOT NULL,
    "dem400" DOUBLE PRECISION NOT NULL,
    "ppt_mon_hist" DOUBLE PRECISION[] NOT NULL,
    "tave_mon_hist" DOUBLE PRECISION[] NOT NULL,
    "pas_mon_hist" DOUBLE PRECISION[] NOT NULL,
    "pas_mon_fut_min" DOUBLE PRECISION[] NOT NULL,
    "pas_mon_fut_max" DOUBLE PRECISION[] NOT NULL,
    "ppt_mon_fut_min" DOUBLE PRECISION[] NOT NULL,
    "ppt_mon_fut_max" DOUBLE PRECISION[] NOT NULL,
    "tave_mon_fut_min" DOUBLE PRECISION[] NOT NULL,
    "tave_mon_fut_max" DOUBLE PRECISION[] NOT NULL,
    "shrub" DOUBLE PRECISION NOT NULL,
    "grassland" DOUBLE PRECISION NOT NULL,
    "coniferous" DOUBLE PRECISION NOT NULL,
    "water" DOUBLE PRECISION NOT NULL,
    "snow" DOUBLE PRECISION NOT NULL,
    "developed" DOUBLE PRECISION NOT NULL,
    "wetland" DOUBLE PRECISION NOT NULL,
    "herb" DOUBLE PRECISION NOT NULL,
    "deciduous" DOUBLE PRECISION NOT NULL,
    "mixed" DOUBLE PRECISION NOT NULL,
    "barren" DOUBLE PRECISION NOT NULL,
    "cropland" DOUBLE PRECISION NOT NULL,
    "mad_m3s" numeric NOT NULL,
    "mad_m3yr" numeric NOT NULL,
    "qmon_m3s" numeric[] NOT NULL,
    "rr" boolean NOT NULL,
    "downstream_id" integer NOT NULL,
    "summer_sensitivity" boolean NOT NULL,
    "winter_sensitivity" boolean NOT NULL,
    "elevs" DOUBLE PRECISION[],
    "mgmt_lng" DOUBLE PRECISION NOT NULL,
    "mgmt_lat" DOUBLE PRECISION NOT NULL,
    "gnis_name" text DEFAULT '',
    "downstream_area" DOUBLE PRECISION NOT NULL,
    "query_polygon" json NOT NULL,
    "mgmt_polygon" json NOT NULL,
    "ws_area_km" numeric NOT NULL,
    "local_watershed_order" smallint
    );

    CREATE TABLE "bcwat_ws"."ws_geom_all_report" (
    "watershed_feature_id" integer PRIMARY KEY,
    "fwa_watershed_code" text DEFAULT '',
    "local_watershed_code" text DEFAULT '',
    "upstream_geom_4326_z12" geometry(Geometry,4326),
    "area" DOUBLE PRECISION NOT NULL,
    "lon4326" DOUBLE PRECISION NOT NULL,
    "lat4326" DOUBLE PRECISION NOT NULL,
    "gnis_name" text DEFAULT '',
    "upstream_geom4326" geometry(geometry,4326) NOT NULL,
    "local_watershed_order" smallint
    );

    CREATE TABLE "bcwat_ws"."fdc" (
    "watershed_feature_id" integer,
    "month" smallint,
    "percs" smallint[] NOT NULL,
    "c1" text NOT NULL DEFAULT '',
    "q_m3s_c1" DOUBLE PRECISION[] NOT NULL,
    "c2" text NOT NULL DEFAULT '',
    "q_m3s_c2" DOUBLE PRECISION[] NOT NULL,
    "c3" text NOT NULL DEFAULT '',
    "q_m3s_c3" DOUBLE PRECISION[] NOT NULL,
    "percs_all" smallint[] NOT NULL,
    "q_m3s_c1_all" DOUBLE PRECISION[] NOT NULL,
    PRIMARY KEY ("watershed_feature_id", "month")
    );

    CREATE TABLE "bcwat_ws"."fdc_physical" (
    "watershed_feature_id" integer PRIMARY KEY,
    "lat" DOUBLE PRECISION,
    "lon" DOUBLE PRECISION,
    "upstream_area_km2" DOUBLE PRECISION,
    "min_elev" DOUBLE PRECISION,
    "avg_elev" DOUBLE PRECISION,
    "max_elev" DOUBLE PRECISION,
    "month" smallint[],
    "ppt" DOUBLE PRECISION[],
    "tave" DOUBLE PRECISION[],
    "pas" DOUBLE PRECISION[]
    );

    CREATE TABLE "bcwat_ws"."fdc_distance" (
    "watershed_feature_id" integer,
    "candidate" text,
    "month01" DOUBLE PRECISION,
    "month02" DOUBLE PRECISION,
    "month03" DOUBLE PRECISION,
    "month04" DOUBLE PRECISION,
    "month05" DOUBLE PRECISION,
    "month06" DOUBLE PRECISION,
    "month07" DOUBLE PRECISION,
    "month08" DOUBLE PRECISION,
    "month09" DOUBLE PRECISION,
    "month10" DOUBLE PRECISION,
    "month11" DOUBLE PRECISION,
    "month12" DOUBLE PRECISION,
    PRIMARY KEY ("watershed_feature_id", "candidate")
    );

    CREATE TABLE "bcwat_ws"."geo_feature" (
    "geo_feature_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "geoname" text NOT NULL,
    "x" numeric NOT NULL,
    "y" numeric NOT NULL,
    "zoom" integer,
    "geocomment" text DEFAULT '',
    "concisecode" text DEFAULT '',
    "geom4326" geometry(Point, 4326),
    "dt_imported" timestamptz
    );
    
    CREATE TABLE "bcwat_ws"."mapsearch2" (
    "mapsearch_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "geoname" text NOT NULL,
    "x" numeric NOT NULL,
    "y" numeric NOT NULL,
    "zoom" integer,
    "geocomment" text DEFAULT '',
    "concisecode" text DEFAULT ''
    );

    CREATE TABLE "bcwat_ws"."lake" (
    "waterbody_poly_id" integer PRIMARY KEY,
    "geom4326" geometry(MultiPolygon,4326),
    "geom3005" geometry(MultiPolygon,3005),
    "gnis_name_1" text DEFAULT '',
    "area_m2" DOUBLE PRECISION,
    "fwa_watershed_code" text DEFAULT '',
    "local_watershed_code" text DEFAULT '',
    "geom4326_buffer_100" geometry(MultiPolygon,4326),
    "winter_allocs_m3" DOUBLE PRECISION
    );

    CREATE TABLE "bcwat_ws"."fwa_stream_name" (
    "linear_feature_id" integer PRIMARY KEY,
    "fwa_watershed_code" text DEFAULT '',
    "gnis_name" text DEFAULT '',
    "stream_magnitude" integer,
    "geom" geometry(MultiLineString,3005),
    "point_on_line" geometry(Point,3005)
    );

    CREATE TABLE "bcwat_ws"."fwa_stream_name_unique" (
    "fwa_watershed_code" text PRIMARY KEY,
    "gnis_name" text DEFAULT ''
    );

    -- FOREIGN KEYS --

    ALTER TABLE "bcwat_ws"."fund_rollup" ADD CONSTRAINT "fund_rollup_watershed_feature_id_fkey" FOREIGN KEY ("watershed_feature_id") REFERENCES "bcwat_ws"."fwa_fund" ("watershed_feature_id");

    ALTER TABLE "bcwat_ws"."fund_rollup_report" ADD CONSTRAINT "funds_rollup_report_watershed_feature_id_fkey" FOREIGN KEY ("watershed_feature_id") REFERENCES "bcwat_ws"."fwa_fund" ("watershed_feature_id");

    ALTER TABLE "bcwat_ws"."ws_geom_all_report" ADD CONSTRAINT "ws_geom_all_report_watershed_feature_id_fkey" FOREIGN KEY ("watershed_feature_id") REFERENCES "bcwat_ws"."fwa_fund" ("watershed_feature_id");

    ALTER TABLE "bcwat_ws"."fdc_physical" ADD CONSTRAINT "fdc_physical_watershed_feature_id_fkey" FOREIGN KEY ("watershed_feature_id") REFERENCES "bcwat_ws"."fwa_fund" ("watershed_feature_id");

    -- COMMENTS --

    COMMENT ON SCHEMA "bcwat_ws" IS 'The full name of bcwat_ws is bcwat_watershed. This schema consists of watershed data as well as data that is based on the watershed (topography, watershed climate, etc.)';
'''