bcwat_ws_query = '''

    CREATE SCHEMA "bcwat_ws";

    -- TABLE CREATION --

    CREATE TABLE "bcwat_ws"."fwa_fund" (
    "watershed_feature_id" integer PRIMARY KEY,
    "fwa_watershed_code" text,
    "local_watershed_code" text,
    "the_geom" geometry(MultiPolygon, 3005),
    "centroid" geometry(Point, 3005),
    "lake_name" text,
    "report" smallint,
    "local_watershed_order" integer,
    "has_upstream" boolean DEFAULT false,
    "in_study_area" boolean NOT NULL DEFAULT false,
    "point_inside_poly" geometry(Point,3005),
    "lake" boolean DEFAULT false,
    "area" DOUBLE PRECISION,
    "geom4326" geometry(MultiPolygon,4326),
    "point_inside_poly4326" geometry(Point, 4326),
    "pip_x4326" DOUBLE PRECISION,
    "pip_y4326" DOUBLE PRECISION,
    "watershed_feature_id_foundry_eca" integer,
    "has_netcdf" boolean DEFAULT false
    );

    CREATE TABLE "bcwat_ws"."fwa_union" (
    "fwa_watershed_code" text PRIMARY KEY,
    "geom_simp4326" geometry(MultiPolygon,4326)
    );

    CREATE TABLE "bcwat_ws"."fund_rollup_report" (
    "watershed_feature_id" integer PRIMARY KEY,
    "downstream_id" integer NOT NULL,
    "watershed_metadata" JSON NOT NULL
    );

    CREATE TABLE "bcwat_ws"."ws_geom_all_report" (
    "watershed_feature_id" integer PRIMARY KEY,
    "fwa_watershed_code" text,
    "local_watershed_code" text,
    "upstream_geom_4326_z12" geometry(Geometry,4326),
    "area_m2" DOUBLE PRECISION NOT NULL,
    "longitude" DOUBLE PRECISION NOT NULL,
    "latitude" DOUBLE PRECISION NOT NULL,
    "gnis_name" text,
    "number_of_points_in_polygon" BIGINT
    );

    CREATE TABLE "bcwat_ws"."fdc" (
    "watershed_feature_id" integer,
    "month" smallint,
    "month_value" json,
    PRIMARY KEY ("watershed_feature_id", "month")
    );

    CREATE TABLE "bcwat_ws"."fdc_physical" (
    "watershed_feature_id" integer PRIMARY KEY,
    "watershed_fdc_data" JSON
    );

    CREATE TABLE "bcwat_ws"."fdc_distance" (
    "watershed_feature_id" integer,
    "candidate" text,
    "candidate_month_value" json,
    PRIMARY KEY ("watershed_feature_id", "candidate")
    );

    CREATE TABLE "bcwat_ws"."geo_feature" (
    "geo_feature_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "geoname" text NOT NULL,
    "x" DOUBLE PRECISION NOT NULL,
    "y" DOUBLE PRECISION NOT NULL,
    "zoom" integer,
    "geocomment" text,
    "concisecode" text,
    "geom4326" geometry(Point, 4326),
    "dt_imported" timestamptz
    );

    CREATE TABLE "bcwat_ws"."mapsearch2" (
    "mapsearch_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "geoname" text NOT NULL,
    "x" DOUBLE PRECISION NOT NULL,
    "y" DOUBLE PRECISION NOT NULL,
    "zoom" integer,
    "geocomment" text,
    "concisecode" text
    );

    CREATE TABLE "bcwat_ws"."lake" (
    "waterbody_poly_id" integer PRIMARY KEY,
    "geom4326" geometry(MultiPolygon,4326),
    "gnis_name" text,
    "area_m2" DOUBLE PRECISION,
    "fwa_watershed_code" text,
    "local_watershed_code" text,
    "geom4326_buffer_100" geometry(MultiPolygon,4326),
    "winter_allocs_m3" DOUBLE PRECISION
    );

    CREATE TABLE "bcwat_ws"."fwa_stream_name" (
    "linear_feature_id" integer PRIMARY KEY,
    "fwa_watershed_code" text,
    "gnis_name" text,
    "stream_magnitude" integer,
    "geom" geometry(MultiLineString,3005),
    "point_on_line" geometry(Point,3005)
    );

    CREATE TABLE "bcwat_ws"."fwa_stream_name_unique" (
    "fwa_watershed_code" text PRIMARY KEY,
    "gnis_name" text
    );

    -- FOREIGN KEYS --

    ALTER TABLE "bcwat_ws"."fund_rollup_report" ADD CONSTRAINT "funds_rollup_report_watershed_feature_id_fkey" FOREIGN KEY ("watershed_feature_id") REFERENCES "bcwat_ws"."fwa_fund" ("watershed_feature_id");

    ALTER TABLE "bcwat_ws"."ws_geom_all_report" ADD CONSTRAINT "ws_geom_all_report_watershed_feature_id_fkey" FOREIGN KEY ("watershed_feature_id") REFERENCES "bcwat_ws"."fwa_fund" ("watershed_feature_id");

    -- COMMENTS --

    COMMENT ON SCHEMA "bcwat_ws" IS 'The full name of bcwat_ws is bcwat_watershed. This schema consists of watershed data as well as data that is based on the watershed (topography, watershed climate, etc.)';
'''
