bcwat_obs_query = '''

    CREATE SCHEMA "bcwat_obs";

    -- TABLE CREATION --

    CREATE TABLE "bcwat_obs"."station" (
    "station_id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "original_id" text NOT NULL,
    "network_id" smallint NOT NULL,
    "type_id" smallint NOT NULL,
    "station_name" text NOT NULL,
    "stream_name" text DEFAULT '',
    "station_description" text DEFAULT '',
    "station_status_id" integer,
    "operation_id" integer,
    "longitude" DOUBLE PRECISION NOT NULL,
    "latitude" DOUBLE PRECISION NOT NULL,
    "geom4326" geometry NOT NULL,
    "drainage_area" DOUBLE PRECISION,
    "scrape" bool NOT NULL DEFAULT true,
    "regulated" bool NOT NULL DEFAULT false,
    "user_flag" bool NOT NULL DEFAULT false
    );

    CREATE TABLE "bcwat_obs"."network" (
    "network_id" smallint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "network_name" text NOT NULL,
    "licence_link" text DEFAULT '',
    "description" text DEFAULT '',
    "redistribute" boolean NOT NULL DEFAULT false,
    "provided_qa" boolean NOT NULL DEFAULT false,
    "network_type" varchar(2)
    );

    CREATE TABLE "bcwat_obs"."station_type" (
    "type_id" smallint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "type_name" text NOT NULL,
    "type_description" text DEFAULT ''
    );

    CREATE TABLE "bcwat_obs"."station_status" (
    "status_id" smallint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "status_name" text NOT NULL
    );

    CREATE TABLE "bcwat_obs"."operation" (
    "operation_id" smallint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "operation_name" text,
    "description" text
    );

    CREATE TABLE "bcwat_obs"."variable" (
    "variable_id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "variable_name" text,
    "variable_description" text DEFAULT '',
    "display_name" text NOT NULL,
    "cell_method" text,
    "unit" text
    );

    CREATE TABLE "bcwat_obs"."station_variable" (
    "station_id" bigint,
    "variable_id" smallint,
    PRIMARY KEY ("station_id", "variable_id")
    );

    CREATE TABLE "bcwat_obs"."station_year" (
    "station_id" bigint,
    "year" integer,
    PRIMARY KEY ("station_id", "year")
    );

    CREATE TABLE "bcwat_obs"."qa_type" (
    "qa_type_id" smallint PRIMARY KEY,
    "qa_type_name" text NOT NULL
    );

    CREATE TABLE "bcwat_obs"."water_discharge" (
    "station_id" bigint,
    "variable_id" smallint NOT NULL,
    "datestamp" date,
    "value" DOUBLE PRECISION,
    "qa_id" integer,
    PRIMARY KEY ("station_id", "datestamp")
    );

    CREATE TABLE "bcwat_obs"."water_level" (
    "station_id" bigint,
    "variable_id" smallint NOT NULL,
    "datestamp" date,
    "value" DOUBLE PRECISION,
    "qa_id" integer,
    PRIMARY KEY ("station_id", "datestamp")
    );

    CREATE TABLE "bcwat_obs"."ground_water_level" (
    "station_id" bigint,
    "variable_id" smallint NOT NULL,
    "datestamp" date,
    "value" DOUBLE PRECISION,
    "qa_id" integer,
    PRIMARY KEY ("station_id", "datestamp")
    );

    CREATE TABLE "bcwat_obs"."climate_temperature" (
    "station_id" bigint,
    "variable_id" smallint,
    "datestamp" date,
    "value" DOUBLE PRECISION,
    "qa_id" integer,
    PRIMARY KEY ("station_id", "variable_id", "datestamp")
    );

    CREATE TABLE "bcwat_obs"."climate_precipitation" (
    "station_id" bigint,
    "variable_id" smallint NOT NULL,
    "datestamp" date,
    "value" DOUBLE PRECISION,
    "qa_id" integer,
    PRIMARY KEY ("station_id", "datestamp", "variable_id")
    );

    CREATE TABLE "bcwat_obs"."climate_snow_depth" (
    "station_id" bigint,
    "variable_id" smallint NOT NULL,
    "datestamp" date,
    "value" DOUBLE PRECISION,
    "qa_id" integer,
    PRIMARY KEY ("station_id", "datestamp")
    );

    CREATE TABLE "bcwat_obs"."climate_swe" (
    "station_id" bigint,
    "variable_id" smallint NOT NULL,
    "datestamp" date,
    "value" DOUBLE PRECISION,
    "qa_id" integer,
    PRIMARY KEY ("station_id", "datestamp")
    );

    CREATE TABLE "bcwat_obs"."climate_snow_amount" (
    "station_id" bigint,
    "variable_id" smallint NOT NULL,
    "datestamp" date,
    "value" DOUBLE PRECISION,
    "qa_id" integer,
    PRIMARY KEY ("station_id", "datestamp")
    );

    CREATE TABLE "bcwat_obs"."climate_msp" (
    "station_id" bigint,
    "variable_id" smallint NOT NULL,
    "survey_period" date,
    "datestamp" date NOT NULL,
    "value" DOUBLE PRECISION,
    "code" text,
    "qa_id" integer,
    PRIMARY KEY ("station_id", "survey_period", "variable_id")
    );

    CREATE TABLE "bcwat_obs"."extreme_flow" (
    "station_id" bigint,
    "value" DOUBLE PRECISION,
    "variable_name" text,
    PRIMARY KEY ("station_id", "variable_name")
    );

    CREATE TABLE "bcwat_obs"."climate_wind" (
    "station_id" bigint,
    "variable_id" smallint NOT NULL,
    "datestamp" date,
    "value" DOUBLE PRECISION,
    "qa_id" integer,
    PRIMARY KEY ("station_id", "datestamp", "variable_id")
    );

    CREATE TABLE "bcwat_obs"."flow_metric" (
    "station_id" bigint PRIMARY KEY,
    "station_flow_metric" JSON NOT NULL
    );

    CREATE TABLE "bcwat_obs"."exclude_reason" (
    "exclude_id" smallint PRIMARY KEY,
    "exclude_description" text DEFAULT ''
    );

    CREATE TABLE "bcwat_obs"."wsc_station_year_exclude" (
    "station_id" bigint,
    "dateyear" integer,
    "exclude_id" integer DEFAULT 0,
    PRIMARY KEY ("station_id", "dateyear", "exclude_id")
    );

    CREATE TABLE "bcwat_obs"."climate_hourly" (
    "station_id" bigint,
    "variable_id" smallint,
    "datetimestamp" timestamptz,
    "value" DOUBLE PRECISION,
    "qa_id" smallint,
    PRIMARY KEY ("station_id", "variable_id", "datetimestamp")
    );

    CREATE TABLE "bcwat_obs"."climate_hist" (
    "station_id" bigint,
    "variable_id" smallint,
    "datestamp" date,
    "value" DOUBLE PRECISION,
    "qa_id" smallint,
    PRIMARY KEY ("station_id", "variable_id", "datestamp")
    );

    CREATE TABLE "bcwat_obs"."water_quality_hourly" (
    "station_id" integer,
    "datetimestamp" timestamptz,
    "parameter_id" integer,
    "unit_id" integer,
    "qa_id" smallint NOT NULL DEFAULT 0,
    "location_purpose" text,
    "sampling_agency" text,
    "analyzing_agency" text,
    "collection_method" text,
    "sample_state" text,
    "sample_descriptor" text,
    "analytical_method" text,
    "qa_index_code" text,
    "result" DOUBLE PRECISION NOT NULL,
    "result_text" text NOT NULL,
    "result_letter" text,
    PRIMARY KEY ("station_id", "datetimestamp", "parameter_id", "unit_id")
    );

    CREATE TABLE "bcwat_obs"."water_quality_parameter_grouping" (
    "grouping_id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "grouping_name" text DEFAULT '',
    "parent_group" text DEFAULT '',
    "child_group" text DEFAULT ''
    );

    CREATE TABLE "bcwat_obs"."water_quality_parameter" (
    "parameter_id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "grouping_id" integer,
    "parameter_name" text NOT NULL,
    "parameter_desc" text DEFAULT ''
    );

    CREATE TABLE "bcwat_obs"."water_quality_user_data" (
    "station_id" bigint,
    "datetimestamp" timestamptz,
    "param_name" text,
    "units" text,
    "value" DOUBLE PRECISION NOT NULL,
    "result_letter" text DEFAULT '',
    "parameter_code_units" text DEFAULT '',
    "result_text" text DEFAULT '',
    PRIMARY KEY ("station_id", "datetimestamp", "param_name", "units")
    );

    CREATE TABLE "bcwat_obs"."region" (
    "region_id" smallint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "region_name" text,
    "region_click_studyarea" geometry(MultiPolygon, 4326),
    "region_studyarea_allfunds" geometry(MultiPolygon, 4326)
    );

    CREATE TABLE "bcwat_obs"."station_region" (
    "station_id" bigint,
    "region_id" smallint,
    PRIMARY KEY ("station_id", "region_id")
    );

    CREATE TABLE "bcwat_obs"."project_id" (
    "project_id" smallint PRIMARY KEY,
    "project_name" text,
    "project_geom4326" geometry(MultiPolygon, 4326)
    );

    CREATE TABLE "bcwat_obs"."station_project_id" (
    "station_id" bigint,
    "project_id" smallint,
    PRIMARY KEY ("station_id", "project_id")
    );

    CREATE TABLE "bcwat_obs"."bc_boundary" (
        gid integer PRIMARY KEY,
        geom4326 geometry(Polygon, 4326)
    );

    CREATE TABLE "bcwat_obs"."water_quality_ems_location_type" (
        location_type_code text PRIMARY KEY,
        location_type_description text,
        "include" boolean DEFAULT TRUE
    );

    CREATE TABLE "bcwat_obs"."water_quality_unit" (
        unit_id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        unit_name text
    );

    CREATE TABLE "bcwat_obs"."station_water_quality_parameter" (
        "station_id" bigint,
        "parameter_id" integer,
        PRIMARY KEY ("station_id", "parameter_id")
    );

    -- COMMENTS --

    COMMENT ON COLUMN "bcwat_obs"."flow_metric"."station_flow_metric" IS 'Instantaneous Peak Flow (m3/s) 200yr Return Period
    Instantaneous Peak Flow (m3/s) 100yr Return Period
    Instantaneous Peak Flow (m3/s) 50yr Return Period
    Instantaneous Peak Flow (m3/s) 25yr Return Period
    Instantaneous Peak Flow (m3/s) 20yr Return Period
    Instantaneous Peak Flow (m3/s) 10yr Return Period
    Instantaneous Peak Flow (m3/s) 5yr Return Period
    Instantaneous Peak Flow (m3/s) 2yr Return Period
    Instantaneous Peak Flow (m3/s) 1yr Return Period
    Instantaneous Peak Flow (m3/s) 1.01yr Return Period
    Instantaneous Peak Flow (m3/s) Years of Data
    Annual Mean Flow (high, m3/s) 200yr Return Period
    Annual Mean Flow (high, m3/s) 100yr Return Period
    Annual Mean Flow (high, m3/s) 50yr Return Period
    Annual Mean Flow (high, m3/s) 25yr Return Period
    Annual Mean Flow (high, m3/s) 20yr Return Period
    Annual Mean Flow (high, m3/s) 10yr Return Period
    Annual Mean Flow (high, m3/s) 5yr Return Period
    Annual Mean Flow (high, m3/s) 2yr Return Period
    Annual Mean Flow (high, m3/s) 1yr Return Period
    Annual Mean Flow (high, m3/s) 1.01yr Return Period
    Annual Mean Flow (high, m3/s) Years of Data
    Annual Mean Fow (low, m3/s) 200yr Return Period
    Annual Mean Fow (low, m3/s) 100yr Return Period
    Annual Mean Fow (low, m3/s) 50yr Return Period
    Annual Mean Fow (low, m3/s) 25yr Return Period
    Annual Mean Fow (low, m3/s) 20yr Return Period
    Annual Mean Fow (low, m3/s) 10yr Return Period
    Annual Mean Fow (low, m3/s) 5yr Return Period
    Annual Mean Fow (low, m3/s) 2yr Return Period
    Annual Mean Fow (low, m3/s) 1yr Return Period
    Annual Mean Fow (low, m3/s) 1.01yr Return Period
    Annual Mean Fow (low, m3/s) Years of Data
    June to September 7-Day Low Flow (m3/s) 200yr Return Period
    June to September 7-Day Low Flow (m3/s) 100yr Return Period
    June to September 7-Day Low Flow (m3/s) 50yr Return Period
    June to September 7-Day Low Flow (m3/s) 25yr Return Period
    June to September 7-Day Low Flow (m3/s) 20yr Return Period
    June to September 7-Day Low Flow (m3/s) 10yr Return Period
    June to September 7-Day Low Flow (m3/s) 5yr Return Period
    June to September 7-Day Low Flow (m3/s) 2yr Return Period
    June to September 7-Day Low Flow (m3/s) 1yr Return Period
    June to September 7-Day Low Flow (m3/s) 1.01yr Return Period
    June to September 7-Day Low Flow (m3/s) Years of Data
    Annual 7-day Low Flow (m3/s) 200yr Return Period
    Annual 7-day Low Flow (m3/s) 100yr Return Period
    Annual 7-day Low Flow (m3/s) 50yr Return Period
    Annual 7-day Low Flow (m3/s) 25yr Return Period
    Annual 7-day Low Flow (m3/s) 20yr Return Period
    Annual 7-day Low Flow (m3/s) 10yr Return Period
    Annual 7-day Low Flow (m3/s) 5yr Return Period
    Annual 7-day Low Flow (m3/s) 2yr Return Period
    Annual 7-day Low Flow (m3/s) 1yr Return Period
    Annual 7-day Low Flow (m3/s) 1.01yr Return Period
    Annual 7-day Low Flow (m3/s) Years of Data';

    COMMENT ON COLUMN "bcwat_obs"."variable"."variable_name" IS 'Variable name will be the display name for the data.';

    COMMENT ON COLUMN "bcwat_obs"."variable"."cell_method" IS 'The cell_method is how the cell was initially calculated';

    COMMENT ON SCHEMA "bcwat_obs" IS 'bcwat_obs full name is bcwat_observations. This is where most of the waterportal observations based data and information are kept';

    -- FOREIGN KEYS --

    ALTER TABLE "bcwat_obs"."station" ADD CONSTRAINT "station_station_status_id_fkey" FOREIGN KEY ("station_status_id") REFERENCES "bcwat_obs"."station_status" ("status_id");

    ALTER TABLE "bcwat_obs"."station" ADD CONSTRAINT "station_operation_id_fkey" FOREIGN KEY ("operation_id") REFERENCES "bcwat_obs"."operation" ("operation_id");

    ALTER TABLE "bcwat_obs"."station" ADD CONSTRAINT "station_network_id_fkey" FOREIGN KEY ("network_id") REFERENCES "bcwat_obs"."network" ("network_id");

    ALTER TABLE "bcwat_obs"."station" ADD CONSTRAINT "station_type_id_fkey" FOREIGN KEY ("type_id") REFERENCES "bcwat_obs"."station_type" ("type_id");

    ALTER TABLE "bcwat_obs"."station_variable" ADD CONSTRAINT "station_variable_station_id_fkey" FOREIGN KEY ("station_id") REFERENCES "bcwat_obs"."station" ("station_id");

    ALTER TABLE "bcwat_obs"."station_variable" ADD CONSTRAINT "station_variable_variable_id_fkey" FOREIGN KEY ("variable_id") REFERENCES "bcwat_obs"."variable" ("variable_id");

    ALTER TABLE "bcwat_obs"."station_year" ADD CONSTRAINT "station_year_station_id_fkey" FOREIGN KEY ("station_id") REFERENCES "bcwat_obs"."station" ("station_id");

    ALTER TABLE "bcwat_obs"."water_discharge" ADD CONSTRAINT "water_discharge_station_id_fkey" FOREIGN KEY ("station_id") REFERENCES "bcwat_obs"."station" ("station_id");

    ALTER TABLE "bcwat_obs"."water_discharge" ADD CONSTRAINT "water_discharge_variable_id_fkey" FOREIGN KEY ("variable_id") REFERENCES "bcwat_obs"."variable" ("variable_id");

    ALTER TABLE "bcwat_obs"."water_discharge" ADD CONSTRAINT "water_discharge_qa_id_fkey" FOREIGN KEY ("qa_id") REFERENCES "bcwat_obs"."qa_type" ("qa_type_id");

    ALTER TABLE "bcwat_obs"."water_level" ADD CONSTRAINT "water_level_station_id_fkey" FOREIGN KEY ("station_id") REFERENCES "bcwat_obs"."station" ("station_id");

    ALTER TABLE "bcwat_obs"."water_level" ADD CONSTRAINT "water_level_variable_id_fkey" FOREIGN KEY ("variable_id") REFERENCES "bcwat_obs"."variable" ("variable_id");

    ALTER TABLE "bcwat_obs"."water_level" ADD CONSTRAINT "water_level_qa_id_fkey" FOREIGN KEY ("qa_id") REFERENCES "bcwat_obs"."qa_type" ("qa_type_id");

    ALTER TABLE "bcwat_obs"."ground_water_level" ADD CONSTRAINT "ground_water_level_station_id_fkey" FOREIGN KEY ("station_id") REFERENCES "bcwat_obs"."station" ("station_id");

    ALTER TABLE "bcwat_obs"."ground_water_level" ADD CONSTRAINT "ground_water_level_variable_id_fkey" FOREIGN KEY ("variable_id") REFERENCES "bcwat_obs"."variable" ("variable_id");

    ALTER TABLE "bcwat_obs"."ground_water_level" ADD CONSTRAINT "ground_water_level_qa_id_fkey" FOREIGN KEY ("qa_id") REFERENCES "bcwat_obs"."qa_type" ("qa_type_id");

    ALTER TABLE "bcwat_obs"."climate_temperature" ADD CONSTRAINT "climate_temperature_station_id_fkey" FOREIGN KEY ("station_id") REFERENCES "bcwat_obs"."station" ("station_id");

    ALTER TABLE "bcwat_obs"."climate_temperature" ADD CONSTRAINT "climate_temperature_variable_id_fkey" FOREIGN KEY ("variable_id") REFERENCES "bcwat_obs"."variable" ("variable_id");

    ALTER TABLE "bcwat_obs"."climate_precipitation" ADD CONSTRAINT "climate_precipitation_station_id_fkey" FOREIGN KEY ("station_id") REFERENCES "bcwat_obs"."station" ("station_id");

    ALTER TABLE "bcwat_obs"."climate_precipitation" ADD CONSTRAINT "climate_precipitation_variable_id_fkey" FOREIGN KEY ("variable_id") REFERENCES "bcwat_obs"."variable" ("variable_id");

    ALTER TABLE "bcwat_obs"."climate_snow_depth" ADD CONSTRAINT "climate_snow_depth_station_id_fkey" FOREIGN KEY ("station_id") REFERENCES "bcwat_obs"."station" ("station_id");

    ALTER TABLE "bcwat_obs"."climate_snow_depth" ADD CONSTRAINT "climate_snow_depth_variable_id_fkey" FOREIGN KEY ("variable_id") REFERENCES "bcwat_obs"."variable" ("variable_id");

    ALTER TABLE "bcwat_obs"."climate_swe" ADD CONSTRAINT "climate_swe_station_id_fkey" FOREIGN KEY ("station_id") REFERENCES "bcwat_obs"."station" ("station_id");

    ALTER TABLE "bcwat_obs"."climate_swe" ADD CONSTRAINT "climate_swe_variable_id_fkey" FOREIGN KEY ("variable_id") REFERENCES "bcwat_obs"."variable" ("variable_id");

    ALTER TABLE "bcwat_obs"."climate_msp" ADD CONSTRAINT "climate_msp_station_id_fkey" FOREIGN KEY ("station_id") REFERENCES "bcwat_obs"."station" ("station_id");

    ALTER TABLE "bcwat_obs"."climate_msp" ADD CONSTRAINT "climate_msp_variable_id_fkey" FOREIGN KEY ("variable_id") REFERENCES "bcwat_obs"."variable" ("variable_id");

    ALTER TABLE "bcwat_obs"."extreme_flow" ADD CONSTRAINT "extreme_flow_station_id_fkey" FOREIGN KEY ("station_id") REFERENCES "bcwat_obs"."station" ("station_id");

    ALTER TABLE "bcwat_obs"."flow_metric" ADD CONSTRAINT "flow_metric_station_id_fkey" FOREIGN KEY ("station_id") REFERENCES "bcwat_obs"."station" ("station_id");

    ALTER TABLE "bcwat_obs"."wsc_station_year_exclude" ADD CONSTRAINT "wsc_station_year_exclude" FOREIGN KEY ("station_id") REFERENCES "bcwat_obs"."station" ("station_id");

    ALTER TABLE "bcwat_obs"."wsc_station_year_exclude" ADD CONSTRAINT "wsc_station_year_exclude_exclude_type_fkey" FOREIGN KEY ("exclude_id") REFERENCES "bcwat_obs"."exclude_reason" ("exclude_id");

    ALTER TABLE "bcwat_obs"."water_quality_hourly" ADD CONSTRAINT "water_quality_hourly_qa_id_fkey" FOREIGN KEY ("qa_id") REFERENCES "bcwat_obs"."qa_type" ("qa_type_id");

    ALTER TABLE "bcwat_obs"."water_quality_hourly" ADD CONSTRAINT "water_quality_hourly_parameter_id_fkey" FOREIGN KEY ("parameter_id") REFERENCES "bcwat_obs"."water_quality_parameter" ("parameter_id");

    ALTER TABLE "bcwat_obs"."water_quality_hourly" ADD CONSTRAINT "water_quality_hourly_unit_id_fkey" FOREIGN KEY ("unit_id") REFERENCES "bcwat_obs"."water_quality_unit" ("unit_id");

    ALTER TABLE "bcwat_obs"."water_quality_hourly" ADD CONSTRAINT "water_quality_hourly_station_id_fkey" FOREIGN KEY ("parameter_id") REFERENCES "bcwat_obs"."station" ("station_id");

    ALTER TABLE "bcwat_obs"."climate_hourly" ADD CONSTRAINT "climate_hourly_qa_id_fkey" FOREIGN KEY ("qa_id") REFERENCES "bcwat_obs"."qa_type" ("qa_type_id");

    ALTER TABLE "bcwat_obs"."climate_hourly" ADD CONSTRAINT "climate_houly_station_id_fkey" FOREIGN KEY ("station_id") REFERENCES "bcwat_obs"."station" ("station_id");

    ALTER TABLE "bcwat_obs"."climate_hourly" ADD CONSTRAINT "climate_hourly_variable_id_fkey" FOREIGN KEY ("variable_id") REFERENCES "bcwat_obs"."variable" ("variable_id");

    ALTER TABLE "bcwat_obs"."water_quality_parameter" ADD CONSTRAINT "water_quality_parameter_grouping_grouping_id_fkey" FOREIGN KEY ("grouping_id") REFERENCES "bcwat_obs"."water_quality_parameter_grouping" ("grouping_id");

    ALTER TABLE "bcwat_obs"."water_quality_user_data" ADD CONSTRAINT "water_uality_user_data_station_id_fkey" FOREIGN KEY ("station_id") REFERENCES "bcwat_obs"."station" ("station_id");

    ALTER TABLE "bcwat_obs"."station_region" ADD CONSTRAINT "station_region_station_id_fkey" FOREIGN KEY ("station_id") REFERENCES "bcwat_obs"."station" ("station_id");

    ALTER TABLE "bcwat_obs"."station_region" ADD CONSTRAINT "station_region_region_id_fkey" FOREIGN KEY ("region_id") REFERENCES "bcwat_obs"."region" ("region_id");

    ALTER TABLE "bcwat_obs"."station_project_id" ADD CONSTRAINT "station_project_id_station_id_fkey" FOREIGN KEY ("station_id") REFERENCES "bcwat_obs"."station" ("station_id");

    ALTER TABLE "bcwat_obs"."station_project_id" ADD CONSTRAINT "station_project_id_project_id_fkey" FOREIGN KEY ("project_id") REFERENCES "bcwat_obs"."project_id" ("project_id");

    ALTER TABLE "bcwat_obs"."climate_msp" ADD CONSTRAINT "climate_msp_qa_id_fkey" FOREIGN KEY ("qa_id") REFERENCES "bcwat_obs"."qa_type" ("qa_type_id");

    ALTER TABLE "bcwat_obs"."climate_precipitation" ADD CONSTRAINT "climate_precipitation_qa_id_fkey" FOREIGN KEY ("qa_id") REFERENCES "bcwat_obs"."qa_type" ("qa_type_id");

    ALTER TABLE "bcwat_obs"."climate_snow_depth" ADD CONSTRAINT "climate_snow_depth_qa_id_fkey" FOREIGN KEY ("qa_id") REFERENCES "bcwat_obs"."qa_type" ("qa_type_id");

    ALTER TABLE "bcwat_obs"."climate_swe" ADD CONSTRAINT "climate_swe_qa_id_fkey" FOREIGN KEY ("qa_id") REFERENCES "bcwat_obs"."qa_type" ("qa_type_id");

    ALTER TABLE "bcwat_obs"."climate_temperature" ADD CONSTRAINT "climate_temperature_qa_id_fkey" FOREIGN KEY ("qa_id") REFERENCES "bcwat_obs"."qa_type" ("qa_type_id");

    ALTER TABLE "bcwat_obs"."climate_wind" ADD CONSTRAINT "climate_wind_qa_id_fkey" FOREIGN KEY ("qa_id") REFERENCES "bcwat_obs"."qa_type" ("qa_type_id");

    ALTER TABLE "bcwat_obs"."climate_wind" ADD CONSTRAINT "climate_wind_station_id_fkey" FOREIGN KEY ("station_id") REFERENCES "bcwat_obs"."station" ("station_id");

    ALTER TABLE "bcwat_obs"."climate_wind" ADD CONSTRAINT "climate_wind_variable_id_fkey" FOREIGN KEY ("variable_id") REFERENCES "bcwat_obs"."variable" ("variable_id");

    ALTER TABLE "bcwat_obs"."climate_snow_amount" ADD CONSTRAINT "climate_snow_amount_qa_id_fkey" FOREIGN KEY ("qa_id") REFERENCES "bcwat_obs"."qa_type" ("qa_type_id");

    ALTER TABLE "bcwat_obs"."climate_snow_amount" ADD CONSTRAINT "climate_snow_amount_station_id_fkey" FOREIGN KEY ("station_id") REFERENCES "bcwat_obs"."station" ("station_id");

    ALTER TABLE "bcwat_obs"."climate_snow_amount" ADD CONSTRAINT "climate_snow_amount_variable_id_fkey" FOREIGN KEY ("variable_id") REFERENCES "bcwat_obs"."variable" ("variable_id");

    ALTER TABLE "bcwat_obs"."climate_hist" ADD CONSTRAINT "climate_hist_station_id_fkey" FOREIGN KEY ("station_id") REFERENCES "bcwat_obs"."station" ("station_id");

    ALTER TABLE "bcwat_obs"."climate_hist" ADD CONSTRAINT "climate_hist_variable_id_fkey" FOREIGN KEY ("variable_id") REFERENCES "bcwat_obs"."variable" ("variable_id");

    ALTER TABLE "bcwat_obs"."climate_hist" ADD CONSTRAINT "climate_hist_qa_id_fkey" FOREIGN KEY ("qa_id") REFERENCES "bcwat_obs"."qa_type" ("qa_type_id");

    ALTER TABLE "bcwat_obs"."station_water_quality_parameter" ADD CONSTRAINT "station_water_quality_parameter_station_id_fkey" FOREIGN KEY ("station_id") REFERENCES "bcwat_obs"."station" ("station_id");

    ALTER TABLE "bcwat_obs"."station_water_quality_parameter" ADD CONSTRAINT "station_water_quality_parameter_parameter_id_fkey" FOREIGN KEY ("parameter_id") REFERENCES "bcwat_obs"."water_quality_parameter" ("parameter_id");

    -- CHECK CONSTRAINTS --

    ALTER TABLE "bcwat_obs"."ground_water_level" ADD CONSTRAINT "ground_water_level_check_value_not_negative" CHECK ("value" >= 0);

    ALTER TABLE "bcwat_obs"."climate_precipitation" ADD CONSTRAINT "climate_precipitation_check_value_not_negative" CHECK ("value" >= 0);

    ALTER TABLE "bcwat_obs"."climate_snow_depth" ADD CONSTRAINT "climate_snow_depth_check_value_not_negative" CHECK ("value" >= 0);

    ALTER TABLE "bcwat_obs"."climate_swe" ADD CONSTRAINT "climate_swe_check_value_not_negative" CHECK ("value" >= 0);

    ALTER TABLE "bcwat_obs"."climate_msp" ADD CONSTRAINT "climate_msp_check_value_not_negative" CHECK ("value" >= 0);

    ALTER TABLE "bcwat_obs"."extreme_flow" ADD CONSTRAINT "extreme_flow_check_value_not_negative" CHECK ("value" >= 0);

-- VIEWS --

    CREATE OR REPLACE VIEW bcwat_obs.scrape_station AS
        SELECT
            station.original_id,
            station.station_id,
            'wsc'::text AS station_data_source
        FROM
            bcwat_obs.station
        WHERE
            network_id = 1
        AND
            station.scrape = true
        OR
            (station.original_id = ANY (ARRAY['09AA010'::character varying::text, '09AA014'::character varying::text, '09AA015'::character varying::text, '09AE004'::character varying::text]))
    UNION ALL
        SELECT
            station.original_id,
            station.station_id,
            'flowworks'::text AS station_data_source
        FROM
            bcwat_obs.station
        WHERE
            network_id IN (3, 50)
        AND
            station.scrape = true
    UNION ALL
        SELECT
            station.original_id,
            station.station_id,
            'surrey_wsc'::text AS station_data_source
        FROM
            bcwat_obs.station
        WHERE
            network_id = 1
        AND
            (station.station_id IN (
                SELECT
                    station_project_id.station_id
                FROM
                    bcwat_obs.station_project_id
                WHERE
                    station_project_id.project_id = 2)
            )
        AND
            station.scrape = true
    UNION ALL
        SELECT
            station.original_id,
            station.station_id,
            'surrey_scada'::text AS station_data_source
        FROM
            bcwat_obs.station
        WHERE
            network_id = 4
        AND
            station.scrape = true
    UNION ALL
        SELECT
            station.original_id,
            station.station_id,
            'delta'::text AS station_data_source
        FROM
            bcwat_obs.station
        WHERE
            network_id = 5
        AND
            station.scrape = true
    UNION ALL
        SELECT
            station.original_id,
            station.station_id,
            'nfld_dec'::text AS station_data_source
        FROM
            bcwat_obs.station
        WHERE
            network_id = 2
        AND
            station.scrape = true
    UNION ALL
        SELECT
            'OW'::text || lpad(station.original_id, 3, '0'::text) AS original_id,
            station.station_id,
            'gw'::text AS station_data_source
        FROM
            bcwat_obs.station
        WHERE
            network_id = 10
        AND
            station.scrape = true
    UNION ALL
        SELECT
            station.original_id,
            station.station_id,
            'datamart'::text AS station_data_source
        FROM
            bcwat_obs.station
        WHERE
            network_id = 21
        AND
            station.scrape = true
    UNION ALL
        SELECT
            station.original_id,
            station.station_id,
            'moti'::text AS station_data_source
        FROM
            bcwat_obs.station
        WHERE
            network_id = 20
        AND
            station.scrape = true
    UNION ALL
        SELECT
            station.original_id,
            station.station_id,
            'asp'::text AS station_data_source
        FROM
            bcwat_obs.station
        WHERE
            network_id = 19
        AND
            station.scrape = true
    UNION ALL
        SELECT
            station.original_id,
            station.station_id,
            'bch'::text AS station_data_source
        FROM
            bcwat_obs.station
        WHERE
            network_id = 14
        AND
            station.scrape = true
    UNION ALL
        SELECT
            station.original_id,
            station.station_id,
            'msp'::text AS station_data_source
        FROM
            bcwat_obs.station
        WHERE
            type_id = 6
        AND
            network_id = 24
        AND
            station.scrape = true
    UNION ALL
        SELECT
            station.original_id,
            station.station_id,
            'weatherfarmprd'::text AS station_data_source
        FROM
            bcwat_obs.station
        WHERE
            network_id = 30
        AND
            station.scrape = true
    UNION ALL
        SELECT
            station.original_id,
            station.station_id,
            'eccc_wq'::text AS station_data_source
        FROM
            bcwat_obs.station
        WHERE
            network_id = 44
        AND
            station.scrape = true
    UNION ALL
        SELECT
            station.original_id,
            station.station_id,
            'flnro-wmb'::text AS station_data_source
        FROM
            bcwat_obs.station
        WHERE
            network_id = 16
        AND
            station.scrape = true
    UNION ALL
        SELECT
            station.original_id,
            station.station_id,
            'env-hydro'::text AS station_data_source
        FROM
            bcwat_obs.station
        WHERE
            (network_id = ANY (ARRAY[53, 28]))
        AND
            scrape = true
        AND
            type_id = 1
    UNION ALL
        SELECT
            station.original_id,
            station.station_id,
            'env-climate'::text AS station_data_source
        FROM
            bcwat_obs.station
        WHERE
            network_id = 53
        AND
            station.scrape = true
        AND
            type_id = 3
    UNION ALL
        SELECT
            station.original_id,
            station.station_id,
            'env-gw'::text AS station_data_source
        FROM
            bcwat_obs.station
        WHERE
            network_id = 53
        AND
            station.scrape = true
        AND
            type_id = 2
    UNION ALL
        SELECT
            station.original_id,
            station.station_id,
            'env-hydro-surrey'::text AS station_data_source
        FROM
            bcwat_obs.station
        WHERE
            network_id = 53
        AND
            station.scrape = true
        AND
            (station.original_id = ANY (ARRAY['08MH0001'::character varying::text, '08MH0002'::character varying::text]))
        AND
           type_id = 1
    UNION ALL
        SELECT
            station.original_id,
            station.station_id,
            'env-aqn'::text AS station_data_source
        FROM
            bcwat_obs.station
        WHERE
            network_id = 18
        AND
            station.scrape = true;
'''
