licence_ogc_short_term_approvals = """
    WITH datas AS (
        SELECT * FROM cariboo.licence_ogc_short_term_approvals
        UNION
        SELECT * FROM kwt.licence_ogc_short_term_approvals
        UNION
        SELECT * FROM nwwt.licence_ogc_short_term_approvals
        UNION
        SELECT * FROM owt.licence_ogc_short_term_approvals
    )
    SELECT
        fs_id AS short_term_approval_id,
        pod_number,
        short_term_water_use_num,
        water_source_type,
        water_source_type_desc,
        water_source_name,
        purpose,
        purpose_desc,
        approved_volume_per_day,
        approved_total_volume,
        approved_start_date,
        approved_end_date,
        status,
        application_determination_num,
        activity_approval_date,
        activity_cancel_date,
        legacy_ogc_file_number,
        proponent,
        authority_type,
        land_type,
        data_source,
        geom AS geom4326,
        latitude,
        longitude,
        is_consumptive,
        qty_display
    FROM datas;
"""

bc_wls_wrl_wra = """
    WITH licence AS (
        SELECT
            fs_id AS wls_wrl_wra_id,
            licence_no,
            tpod_tag,
            purpose,
            pcl_no,
            qty_original,
            qty_flag,
            qty_units,
            licensee,
            lic_status_date,
            priority_date,
            expiry_date,
            longitude,
            latitude,
            stream_name,
            quantity_day_m3,
            quantity_sec_m3,
            quantity_ann_m3,
            lic_status,
            rediversion_flag,
            flag_desc,
            file_no,
            water_allocation_type,
            geom AS geom4326,
            water_source_type_desc,
            hydraulic_connectivity,
            well_tag_number,
            related_licences,
            'Domestic' AS industry_activity,
            'Domestic' AS purpose_groups,
            is_consumptive,
            ann_adjust,
            quantity_ann_m3_storage_adjust,
            documentation::jsonb,
            qty_display,
            puc_groupings_storage,
            date_updated
        FROM cariboo.bc_wls_wrl_wra
        WHERE puc_groupings_storage = 'Domestic'
        UNION
        SELECT
            fs_id AS wls_wrl_wra_id,
            licence_no,
            tpod_tag,
            purpose,
            pcl_no,
            qty_original,
            qty_flag,
            qty_units,
            licensee,
            lic_status_date,
            priority_date,
            expiry_date,
            longitude,
            latitude,
            stream_name,
            quantity_day_m3,
            quantity_sec_m3,
            quantity_ann_m3,
            lic_status,
            rediversion_flag,
            flag_desc,
            file_no,
            water_allocation_type,
            geom AS geom4326,
            water_source_type_desc,
            hydraulic_connectivity,
            well_tag_number,
            related_licences,
            industry_activity,
            purpose_groups,
            is_consumptive,
            ann_adjust,
            quantity_ann_m3_storage_adjust,
            documentation::jsonb,
            qty_display,
            puc_groupings_storage,
            date_updated
        FROM cariboo.bc_wls_wrl_wra
        WHERE puc_groupings_storage != 'Domestic'
        UNION
        SELECT
            fs_id AS wls_wrl_wra_id,
            licence_no,
            tpod_tag,
            purpose,
            pcl_no,
            qty_original,
            qty_flag,
            qty_units,
            licensee,
            lic_status_date,
            priority_date,
            expiry_date,
            longitude,
            latitude,
            stream_name,
            quantity_day_m3,
            quantity_sec_m3,
            quantity_ann_m3,
            lic_status,
            rediversion_flag,
            flag_desc,
            file_no,
            water_allocation_type,
            geom AS geom4326,
            water_source_type_desc,
            hydraulic_connectivity,
            well_tag_number,
            related_licences,
            'Domestic' AS industry_activity,
            'Domestic' AS purpose_groups,
            is_consumptive,
            ann_adjust,
            NULL AS quantity_ann_m3_storage_adjust,
            documentation::jsonb,
            qty_display,
            puc_groupings_storage,
            date_updated
        FROM kwt.bc_wls_wrl_wra
        WHERE puc_groupings_storage = 'Domestic'
        UNION
        SELECT
            fs_id AS wls_wrl_wra_id,
            licence_no,
            tpod_tag,
            purpose,
            pcl_no,
            qty_original,
            qty_flag,
            qty_units,
            licensee,
            lic_status_date,
            priority_date,
            expiry_date,
            longitude,
            latitude,
            stream_name,
            quantity_day_m3,
            quantity_sec_m3,
            quantity_ann_m3,
            lic_status,
            rediversion_flag,
            flag_desc,
            file_no,
            water_allocation_type,
            geom AS geom4326,
            water_source_type_desc,
            hydraulic_connectivity,
            well_tag_number,
            related_licences,
            industry_activity,
            purpose_groups,
            is_consumptive,
            ann_adjust,
            NULL AS quantity_ann_m3_storage_adjust,
            documentation::jsonb,
            qty_display,
            puc_groupings_storage,
            date_updated
        FROM kwt.bc_wls_wrl_wra
        WHERE puc_groupings_storage != 'Domestic'
        UNION
        SELECT
            fs_id AS wls_wrl_wra_id,
            licence_no,
            tpod_tag,
            purpose,
            pcl_no,
            qty_original,
            qty_flag,
            qty_units,
            licensee,
            lic_status_date,
            priority_date,
            expiry_date,
            longitude,
            latitude,
            stream_name,
            quantity_day_m3,
            quantity_sec_m3,
            quantity_ann_m3,
            lic_status,
            rediversion_flag,
            flag_desc,
            file_no,
            water_allocation_type,
            geom AS geom4326,
            water_source_type_desc,
            hydraulic_connectivity,
            well_tag_number,
            related_licences,
            industry_activity,
            purpose_groups,
            is_consumptive,
            ann_adjust,
            NULL AS quantity_ann_m3_storage_adjust,
            documentation::jsonb,
            qty_display,
            puc_groupings_storage,
            date_updated
        FROM nwwt.bc_wls_wrl_wra
        UNION
        SELECT
            fs_id AS wls_wrl_wra_id,
            licence_no,
            tpod_tag,
            purpose,
            pcl_no,
            qty_original,
            qty_flag,
            qty_units,
            licensee,
            lic_status_date,
            priority_date,
            expiry_date,
            longitude,
            latitude,
            stream_name,
            quantity_day_m3,
            quantity_sec_m3,
            quantity_ann_m3,
            lic_status,
            rediversion_flag,
            flag_desc,
            file_no,
            water_allocation_type,
            geom AS geom4326,
            water_source_type_desc,
            hydraulic_connectivity,
            well_tag_number,
            related_licences,
            industry_activity,
            purpose_groups,
            is_consumptive,
            ann_adjust,
            NULL AS quantity_ann_m3_storage_adjust,
            documentation::jsonb,
            qty_display,
            puc_groupings_storage,
            date_updated
        FROM owt.bc_wls_wrl_wra
    )
    SELECT
        wls_wrl_wra_id,
        licence_no,
        tpod_tag,
        purpose,
        pcl_no,
        qty_original,
        qty_flag,
        qty_units,
        licensee,
        lic_status_date,
        priority_date,
        expiry_date,
        longitude,
        latitude,
        stream_name,
        quantity_day_m3,
        quantity_sec_m3,
        quantity_ann_m3,
        lic_status,
        rediversion_flag,
        flag_desc,
        file_no,
        water_allocation_type,
        geom4326,
        water_source_type_desc,
        hydraulic_connectivity,
        well_tag_number,
        related_licences,
        industry_activity,
        purpose_groups,
        is_consumptive,
        max(ann_adjust) AS ann_adjust,
        max(quantity_ann_m3_storage_adjust) AS quantity_ann_m3_storage_adjust,
        documentation,
        qty_display,
        puc_groupings_storage,
        date_updated
    FROM licence
    GROUP BY
        wls_wrl_wra_id,
        licence_no,
        tpod_tag,
        purpose,
        pcl_no,
        qty_original,
        qty_flag,
        qty_units,
        licensee,
        lic_status_date,
        priority_date,
        expiry_date,
        longitude,
        latitude,
        stream_name,
        quantity_day_m3,
        quantity_sec_m3,
        quantity_ann_m3,
        lic_status,
        rediversion_flag,
        flag_desc,
        file_no,
        water_allocation_type,
        geom4326,
        water_source_type_desc,
        hydraulic_connectivity,
        well_tag_number,
        related_licences,
        industry_activity,
        purpose_groups,
        is_consumptive,
        documentation,
        qty_display,
        puc_groupings_storage,
        date_updated
    ORDER BY wls_wrl_wra_id;
"""

licence_bc_purpose = """
    SELECT
        *
    FROM
        water_licences.licence_bc_purpose;
"""

wls_water_approvals_deanna = """
    SELECT
        appfileno,
        proponent,
        podno,
        latitude,
        longitude,
        purpose,
        sourcetype,
        sourcename,
        fishpresence,
        startdate,
        expirationdate,
        ms,
        md,
        my,
        geom AS geom4326,
        fs_id AS deanna_id,
        quantity,
        quantity_units,
        qty_diversion_max_rate,
        qty_units_diversion_max_rate,
        approval_status
    FROM
        water_licences.wls_water_approvals_deanna;
"""

bc_water_approvals = """
    SELECT
        id AS water_approval_id,
        wsd_region,
        approval_type,
        approval_file_number,
        fcbc_tracking_number,
        source,
        works_description,
        quantity,
        quantity_units,
        qty_diversion_max_rate,
        qty_units_diversion_max_rate,
        water_district,
        precinct,
        latitude AS latitude3005,
        longitude AS longitude3005,
        approval_status,
        application_date,
        fcbc_acceptance_date,
        approval_issuance_date,
        approval_start_date,
        approval_expiry_date,
        approval_refuse_abandon_date,
        ST_Transform(geom, 4326) AS geom4326,
        created,
        proponent,
        podno
    FROM
        water_licences.wls_water_approvals
"""

water_management_geoms = """
    SELECT
        gid AS district_id,
        district_n AS district_name,
        ST_Transform(geom, 4326) AS geom4326
    FROM
        water_licences.watmgmt_dist_area_svw
"""
