executor: KubernetesExecutor

extraSecrets:
  airflow-flowworks-credentials:
    type: Opaque
    stringData: |
      BCWAT_FLOWWORKS_PASSWORD: "{{ .Values.secrets.bcwatFlowworks.password }}"
      BCWAT_FLOWWORKS_USERNAME: "{{ .Values.secrets.bcwatFlowworks.username }}"
  airflow-fernet-key:
    type: Opaque
    stringData: |
      fernet-key: "{{ .Values.secrets.fernet.key }}"
  airflow-api-secret-key:
    type: Opaque
    stringData: |
      api-secret-key: "{{ .Values.secrets.api.secretKey }}"
  airflow-jwt-secret:
    type: Opaque
    stringData: |
      jwt-secret: "{{ .Values.secrets.api.jwtKey }}"
  airflow-sendgrid-default:
    type: Opaque
    stringData: |
      auth: '{
          "conn_type": "sendgrid",
          "password": "{{ .Values.secrets.sendgridApiKey }}"
      }'

fernetKeySecretName: airflow-fernet-key
apiSecretKeySecretName: airflow-api-secret-key
jwtSecretName: airflow-jwt-secret

# Airflow database config
# Requires Airflow-metadata secret to have been created, pointing to the external database handling airflow metadata info
data:
  metadataSecretName: airflow-database-connection

registry:
  secretName: acr-pull-secret

airflowVersion: "3.1.7"

images:
  airflow:
    repository: foundrymainregistry.azurecr.io/bcwat/airflow
    tag: latest
    pullPolicy: Always

redis:
  enabled: false

postgresql:
  enabled: false

flower:
  enabled: false

statsd:
  enabled: false

dags:
  persistence:
    enabled: false

# Requires Existing Storage Class Created (handled by FLUX CD - INFRA)
logs:
  persistence:
    enabled: true
    storageClassName: airflow

securityContexts:
  pod:
    runAsNonRoot: true
  containers:
    seccompProfile:
      type: RuntimeDefault

migrateDatabaseJob:
  useHelmHooks: false
  env:
    - name: AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION
      value: "False"
  securityContext:
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault
  ttlSecondsAfterFinished: 180

createUserJob:
  useHelmHooks: false
  env:
    - name: AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION
      value: "False"
  securityContext:
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault
  ttlSecondsAfterFinished: 180

apiServer:
  startupProbe:
    timeoutSeconds: 60
  env:
    - name: AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION
      value: "False"
    - name: PLATFORM
      value: OKD
    - name: AIRFLOW__EXECUTION_API__JWT_EXPIRATION_TIME
      value: "21600"
    - name: AIRFLOW__API_AUTH__JWT_LEEWAY
      value: "60"
  extraInitContainers:
    - name: bcwat-api-init
      image: ~
      imagePullPolicy: Always
      env:
      - name: FLYWAY_URL
        valueFrom:
          secretKeyRef:
            name: bcwat-api-admin-credentials
            key: jdbc-uri
      - name: FLYWAY_USER
        valueFrom:
          secretKeyRef:
            name: bcwat-api-admin-credentials
            key: user
      - name: FLYWAY_PASSWORD
        valueFrom:
          secretKeyRef:
            name: bcwat-api-admin-credentials
            key: password
      resources:
        requests:
          cpu: 50m
          memory: 75Mi
dagProcessor:
  env:
    - name: PLATFORM
      value: OKD
    - name: AIRFLOW__EXECUTION_API__JWT_EXPIRATION_TIME
      value: "21600"
    - name: AIRFLOW__API_AUTH__JWT_LEEWAY
      value: "60"

scheduler:
  env:
    - name: AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION
      value: "False"
    - name: PLATFORM
      value: OKD
    - name: AIRFLOW__EXECUTION_API__JWT_EXPIRATION_TIME
      value: "21600"
    - name: AIRFLOW__API_AUTH__JWT_LEEWAY
      value: "60"
  waitForMigrations:
    enabled: true

triggerer:
  env:
    - name: AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION
      value: "False"
    - name: PLATFORM
      value: OKD
    - name: AIRFLOW__EXECUTION_API__JWT_EXPIRATION_TIME
      value: "21600"
    - name: AIRFLOW__API_AUTH__JWT_LEEWAY
      value: "60"
  persistence:
    enabled: false
  waitForMigrations:
    enabled: true
