images:
  airflow:
    repository: foundrymainregistry.azurecr.io/bcwat/airflow
    tag: latest
    pullPolicy: Always

registry:
  secretName: acr-pull-secret

webserver:
  waitForMigrations:
    enabled: false
  securityContext:
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault

scheduler:
  waitForMigrations:
    enabled: false
  securityContext:
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault

triggerer:
  waitForMigrations:
    enabled: false
  securityContext:
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault

migrateDatabaseJob:
  securityContext:
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault
  ttlSecondsAfterFinished: 180

createUserJob:
  securityContext:
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault
  ttlSecondsAfterFinished: 180
