executor: KubernetesExecutor

config:
  core:
    min_serialized_dag_update_interval: 300
    min_serialized_dag_fetch_interval: 60
  dag_processor:
    min_file_process_interval: 300
    refresh_interval: 3600

extraSecrets:
  airflow-flowworks-credentials:
    type: Opaque
    stringData: |
      BCWAT_FLOWWORKS_PASSWORD: "{{ .Values.secrets.bcwatFlowworks.password }}"
      BCWAT_FLOWWORKS_USERNAME: "{{ .Values.secrets.bcwatFlowworks.username }}"
  airflow-fernet-key:
    type: Opaque
    stringData: |
      fernet-key: "{{ .Values.secrets.fernet.key }}"
  airflow-api-secret-key:
    type: Opaque
    stringData: |
      api-secret-key: "{{ .Values.secrets.api.secretKey }}"
  airflow-jwt-secret:
    type: Opaque
    stringData: |
      jwt-secret: "{{ .Values.secrets.api.jwtKey }}"
  airflow-migrate-db-conn:
    type: Opaque
    stringData: |
      connection: {{ index ((lookup "v1" "Secret" .Release.Namespace "bcwat-dev-crunchy-pguser-airflow-metadata-admin").data) "uri" | b64dec | quote }}
  airflow-rw-db-conn:
    type: Opaque
    stringData: |
      connection: {{ index ((lookup "v1" "Secret" .Release.Namespace "bcwat-dev-crunchy-pguser-airflow-metadata-rw").data) "pgbouncer-uri" | b64dec | quote }}
  bcwat-airflow-rw-db-conn:
    type: Opaque
    stringData: |
      connection: {{ index ((lookup "v1" "Secret" .Release.Namespace "bcwat-dev-crunchy-pguser-bcwat-airflow-read-write").data) "pgbouncer-uri" | b64dec | quote }}
  ches-credentials:
    type: Opaque
    stringData: |
      api-url: "{{ .Values.secrets.ches.apiUrl }}"
      login-url: "{{ .Values.secrets.ches.loginUrl }}"
      client-id: "{{ .Values.secrets.ches.clientId }}"
      client-secret: "{{ .Values.secrets.ches.clientSecret }}"
      from-address: "{{ .Values.secrets.ches.fromAddress }}"
      to-address: "{{ .Values.secrets.ches.toAddress }}"
      subject-prefix: "{{ .Values.secrets.ches.subjectPrefix }}"

fernetKeySecretName: airflow-fernet-key
apiSecretKeySecretName: airflow-api-secret-key
jwtSecretName: airflow-jwt-secret

data:
  metadataSecretName: airflow-rw-db-conn

logs:
  persistence:
    enabled: true
    storageClassName: netapp-file-standard
    size: 8Gi

airflowVersion: "3.1.7"

images:
  airflow:
    repository: ghcr.io/bcgov/nr-bcwat/airflow
    tag: latest
    pullPolicy: Always

securityContext:
  runAsUser: 1018340000
  fsGroup: 1018340000      # a value within the allowed fsGroup range (1018340000/10000)
ingress:
  apiServer:
    enabled: true
    hosts:
      - name: "nr-bcwat-airflow-dev.apps.silver.devops.gov.bc.ca"
        tls:
          enabled: true
    ingressClassName: "openshift-default"
apiServer:
  startupProbe:
    timeoutSeconds: 60
  env:
    - name: AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION
      value: "False"
    - name: PLATFORM
      value: OPENSHIFT
    - name: AIRFLOW__EXECUTION_API__JWT_EXPIRATION_TIME
      value: "21600"
    - name: AIRFLOW__API_AUTH__JWT_LEEWAY
      value: "60"
  networkPolicy:
    ingress:
      from:
        - namespaceSelector:
            matchLabels:
              network.openshift.io/policy-group: ingress
      ports:
        - port: "{{ .Values.ports.apiServer }}"
  extraInitContainers:
    - name: flyway-migrations
      image: "~"
      imagePullPolicy: Always
      env:
        - name: FLYWAY_URL
          valueFrom:
            secretKeyRef:
              name: "~"
              key: jdbc-uri
        - name: FLYWAY_USER
          valueFrom:
            secretKeyRef:
              name: "~"
              key: user
        - name: FLYWAY_PASSWORD
          valueFrom:
            secretKeyRef:
              name: "~"
              key: password
        - name: FLYWAY_BASELINE_ON_MIGRATE
          value: "true"
        - name: FLYWAY_DEFAULT_SCHEMA
          value: "USERS"
        - name: FLYWAY_CONNECT_RETRIES
          value: "10"
        - name: FLYWAY_GROUP
          value: "true"
  waitForMigrations:
    enabled: true

dagProcessor:
  env:
    - name: PLATFORM
      value: OPENSHIFT
    - name: AIRFLOW__EXECUTION_API__JWT_EXPIRATION_TIME
      value: "21600"
    - name: AIRFLOW__API_AUTH__JWT_LEEWAY
      value: "60"

scheduler:
  env:
    - name: AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION
      value: "False"
    - name: PLATFORM
      value: OPENSHIFT
    - name: AIRFLOW__EXECUTION_API__JWT_EXPIRATION_TIME
      value: "21600"
    - name: AIRFLOW__API_AUTH__JWT_LEEWAY
      value: "60"
  waitForMigrations:
    enabled: true

migrateDatabaseJob:
  useHelmHooks: false
  env:
    - name: AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION
      value: "False"
    - name: AIRFLOW__CORE__SQL_ALCHEMY_CONN
      valueFrom:
        secretKeyRef:
          name: airflow-migrate-db-conn
          key: connection
    - name: AIRFLOW__DATABASE__SQL_ALCHEMY_CONN
      valueFrom:
        secretKeyRef:
          name: airflow-migrate-db-conn
          key: connection
    - name: AIRFLOW_CONN_AIRFLOW_DB
      valueFrom:
        secretKeyRef:
          name: airflow-migrate-db-conn
          key: connection
  ttlSecondsAfterFinished: 180

createUserJob:
  useHelmHooks: false
  defaultUser:
    role: Admin
    username: "$(AIRFLOW_ADMIN_USER)"
    email: foundry@foundryspatial.com
    firstName: Foundry
    lastName: Admin
    password: "$(AIRFLOW_ADMIN_PASSWORD)"
  env:
    - name: AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION
      value: "False"
    - name: AIRFLOW__CORE__SQL_ALCHEMY_CONN
      valueFrom:
        secretKeyRef:
          name: airflow-migrate-db-conn
          key: connection
    - name: AIRFLOW__DATABASE__SQL_ALCHEMY_CONN
      valueFrom:
        secretKeyRef:
          name: airflow-migrate-db-conn
          key: connection
    - name: AIRFLOW_CONN_AIRFLOW_DB
      valueFrom:
        secretKeyRef:
          name: airflow-migrate-db-conn
          key: connection
    - name: AIRFLOW_ADMIN_PASSWORD
      valueFrom:
        secretKeyRef:
          name: airflow-api-server-credentials
          key: airflow-admin-password
    - name: AIRFLOW_ADMIN_USER
      valueFrom:
        secretKeyRef:
          name: airflow-api-server-credentials
          key: airflow-admin-user
  ttlSecondsAfterFinished: 180

triggerer:
  env:
    - name: AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION
      value: "False"
    - name: PLATFORM
      value: OPENSHIFT
    - name: AIRFLOW__EXECUTION_API__JWT_EXPIRATION_TIME
      value: "21600"
    - name: AIRFLOW__API_AUTH__JWT_LEEWAY
      value: "60"
  persistence:
    enabled: false
  waitForMigrations:
    enabled: true

postgresql:
  enabled: false
flower:
  enabled: false
statsd:
  enabled: false
dags:
  persistence:
    enabled: false
redis:
  enabled: false
