apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.client.name }}-svc"
  namespace: {{ .Values.global.namespace }}
  labels:
    app: {{ .Values.client.name }}
    project: {{ .Values.global.project }}
spec:
  selector:
    app: {{ .Values.client.name }}
  ports:
    - name: http
      port: {{ .Values.client.port }}
      targetPort: {{ .Values.client.targetPort }}
      protocol: TCP
  type: ClusterIP
