apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.client.name }}-svc"
  namespace: {{ .Values.client.namespace }}
  labels:
    app: {{ .Values.client.name }}
    project: {{ .Values.global.project }}
spec:
  selector:
    app: {{ .Values.client.name }}
  ports:
    - port: 8081
  type: ClusterIP
