apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Values.client.name }}-nginx-conf"
  namespace: {{ .Values.client.namespace }}
  labels:
    app: "{{ .Values.client.name }}"
    project: {{ .Values.global.project }}
data:
  nginx.conf: |
    worker_processes  1;
    error_log  /var/log/nginx/error.log debug;
    pid        /var/run/nginx.pid;

    events {
      worker_connections  1024;
    }

    http {
      include       /etc/nginx/mime.types;
      default_type  application/octet-stream;
      log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                        '$status $body_bytes_sent "$http_referer" '
                        '"$http_user_agent" "$http_x_forwarded_for"';
      access_log  /var/log/nginx/access.log  main;
      sendfile        on;
      keepalive_timeout  125;
      proxy_connect_timeout 125;
      proxy_send_timeout 240;
      proxy_read_timeout 240;

      server {
        listen       8081 default_server;
        listen [::]:8081 default_server;

        server_tokens off;

        add_header Cache-Control "no-cache, no store";
        add_header X-Frame-Options "DENY";

        add_header Expires 0;
        add_header Pragma "no-cache";

        add_header Strict-Transport-Security "max-age=31536000; includeSubDomains;";
        add_header X-Content-Type-Options "nosniff";
        add_header Referrer-Policy "no-referrer";

        add_header X-Permitted-Cross-Domain-Policies "none";

        client_max_body_size 8M;

        location / {
          root   /app;
          index  index.html;
          try_files $uri $uri/ /index.html;
        }

        location /api {
          proxy_pass http://bcwat-api-svc:8000/;
        }

        error_page   500 502 503 504  /50x.html;

        location = /50x.html {
          root   /usr/share/nginx/html;
        }
      }
    }
