apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: airflow-data
  namespace: bcwat
spec:
  accessModes: ReadWriteOnce
  resources:
    requests:
      storage: 15Gi
  storageClassName: airflow
  volumeMode: Filesystem
