apiVersion: v1
kind: PersistentVolume
metadata:
  name: airflow-logs
  namespace: bcwat
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /var/mnt/md0
    server: controlplane0
  persistentVolumeReclaimPolicy: Retain
