global:
  project: bcwat
  namespace: cdd771-dev

frontend:
  name: bcwat-nginx
  image: ghcr.io/bcgov/nr-bcwat/frontend:latest
  port: 80
  targetPort: 3000

backend:
  name: bcwat-api
  image: ghcr.io/bcgov/nr-bcwat/backend:latest
  env:
    FLASK_ENV: Development
    CLIENT_URL: https://nr-bcwat-dev.apps.silver.devops.gov.bc.ca

migrations:
  image: ghcr.io/bcgov/nr-bcwat/migrations:latest
  secret: bcwat-db-crunchy-pguser-bcwat-api-admin


