name: .Helm Airflow Deployer

on:
  workflow_call:
    inputs:
      atomic:
        description: Atomic deployment?  That means fail all or nothing
        default: false
        required: false
        type: boolean
      directory:
        description: Chart directory
        default:  'charts/openshift/airflow'
        required: false
        type: string
      environment:
        description: Environment name; omit for PRs
        required: false
        type: string
      oc_server:
        default: https://api.silver.devops.gov.bc.ca:6443
        description: OpenShift server
        required: false
        type: string
      tag:
        description: Specify a tag to deploy; defaults to PR number
        default: latest
        required: false
        type: string
      triggers:
        description: Paths used to trigger a deployment; e.g. ('./airflow)
        required: false
        type: string

      debug:
        description: Debug mode
        default: false
        required: false
        type: boolean

      ### Usually a bad idea / not recommended
      timeout-minutes:
        description: 'Timeout minutes'
        default: 15
        required: false
        type: number
      values:
        description: 'Values file'
        default: 'values.dev.yaml'
        required: false
        type: string

    outputs:
      tag:
        description: 'Which tag was used for deployment?'
        value: ${{ jobs.deploy.outputs.tag }}
      triggered:
        description: 'Has a deployment has been triggered?'
        value: ${{ jobs.deploy.outputs.triggered }}

    secrets:
      oc_namespace:
        description: OpenShift namespace
        required: true
      oc_token:
        description: OpenShift token
        required: true
      airflow_fernet_key:
        description: Airflow Fernet Key
        required: true
      airflow_flowworks_password:
        description: Airflow Flowworks Password
        required: true
      airflow_flowworks_username:
        description: Airflow Flowworks Username
        required: true
      airflow_webserver_secret_key:
        description: Airflow Webserver Secret Key
        required: true
      airflow_sendgrid_api_key:
        description: Airflow Sendgrid API Key
        required: true


permissions: {}

jobs:
  deploy:
    name: Stack
    environment: ${{ inputs.environment }}
    runs-on: ubuntu-24.04
    outputs:
      tag: ${{ inputs.tag }}
      triggered: ${{ steps.deploy.outputs.triggered }}
    steps:
      - id: vars
        run: |
          # Vars: tag and release

          # Tag defaults to PR number, but can be overridden by inputs.tag
          tag=${{ inputs.tag }}

          # Release name includes run numbers to ensure uniqueness
          release=${{ github.event.repository.name }}-airflow-${{ inputs.environment || inputs.tag }}

          # version, to support helm packaging for non-pr based releases (workflow_dispatch). default to 1.0.0+github run number
          version=1.0.0+${{ github.run_number }}

            # Summary
          echo "tag=${tag}"
          echo "release=${release}"
          echo "version=${version}"

          # Output
          echo "tag=${tag}" >> $GITHUB_OUTPUT
          echo "release=${release}" >> $GITHUB_OUTPUT
          echo "version=${version}" >> $GITHUB_OUTPUT

      - name: Stop pre-existing deployments on PRs (status = pending-upgrade)
        if: github.event_name == 'pull_request'
        uses: bcgov/action-oc-runner@v1.2.2
        with:
          oc_namespace: ${{ secrets.OC_NAMESPACE }}
          oc_token: ${{ secrets.OC_TOKEN }}
          oc_server: ${{ vars.oc_server }}
          triggers: ${{ inputs.triggers }}
          commands: |
            # Interrupt any previous deployments (PR only)
            PREVIOUS=$(helm status ${{ steps.vars.outputs.release }} -o json | jq .info.status || true)
            if [[ ${PREVIOUS} =~ pending ]]; then
              echo "Rollback triggered"
              helm rollback ${{ steps.vars.outputs.release }} || \
                helm uninstall ${{ steps.vars.outputs.release }}
            fi

      - uses: actions/checkout@v4.0.0

      - name: Helm Apache Airflow Install
        run: |
          helm repo add apache-airflow https://airflow.apache.org

      - name: Helm Deploy
        id: deploy
        uses: bcgov/action-oc-runner@v1.2.2
        with:
          oc_namespace: ${{ secrets.OC_NAMESPACE }}
          oc_token: ${{ secrets.OC_TOKEN }}
          oc_server: ${{ vars.oc_server }}
          triggers: ${{ inputs.triggers }}
          ref: ${{ github.ref }}
          commands: |
            # Deploy

            # If directory provided, cd to it
            [ -z "${{ inputs.directory }}" ]|| cd ${{ inputs.directory }}

            # Helm package
            helm package -u . --app-version="tag-${{ steps.vars.outputs.tag }}_run-${{ github.run_number }}" --version=${{ steps.vars.outputs.version }}
            # print the values.yaml file to see the values being used
            # Helm upgrade/rollout
            helm upgrade --install airflow apache-airflow/airflow --version 1.16.0 \
              --wait ${{ inputs.atomic && '--atomic' || '' }} ${{ steps.vars.outputs.release }} \
              --timeout ${{ inputs.timeout-minutes }}m \
              --values ${{ inputs.values }} \
              --set images.airflow.tag=${{ steps.vars.outputs.tag }} \
              --set-string secrets.bcwatFlowworks.password="${{ secrets.airflow_flowworks_password }}" \
              --set-string secrets.bcwatFlowworks.username="${{ secrets.airflow_flowworks_username }}" \
              --set-string secrets.fernet.key="${{ secrets.airflow_fernet_key }}" \
              --set-string secrets.webserver.key="${{ secrets.airflow_webserver_secret_key }}"
              --set-string secrets.sendgridApiKey="${{ secrets.airflow_sendgrid_api_key }}" \
              ./${{ github.event.repository.name }}-${{steps.vars.outputs.version }}.tgz

            # Helm release history
            helm history ${{ steps.vars.outputs.release }}

            # Completed pod cleanup
            oc delete po --field-selector=status.phase==Succeeded || true
