name: .Helm Airflow Deployer

on:
  workflow_call:
    inputs:
      atomic:
        description: Atomic deployment?  That means fail all or nothing
        default: false
        required: false
        type: boolean
      directory:
        description: Chart directory
        default:  'charts/openshift/airflow'
        required: false
        type: string
      environment:
        description: Environment name; omit for PRs
        required: false
        type: string
      oc_server:
        default: https://api.silver.devops.gov.bc.ca:6443
        description: OpenShift server
        required: false
        type: string
      tag:
        description: Specify a tag to deploy; defaults to PR number
        default: latest
        required: false
        type: string
      triggers:
        description: Paths used to trigger a deployment; e.g. ('./airflow)
        required: false
        type: string
      db_user:
        description: The database user
        required: false
        default: bcwat-api-read-only
        type: string
      db_name:
        description: The database name
        required: false
        type: string
        default: bcwat-dev
      debug:
        description: Debug mode
        default: false
        required: false
        type: boolean
      ches_api_url:
        description: CHES API URL
        required: true
        type: string
      ches_login_url:
        description: CHES Login URL
        required: true
        type: string
      ches_from:
        description: CHES From Address
        required: true
        type: string
      ches_to:
        description: CHES To Address
        required: true
        type: string
      ches_subject_prefix:
        description: CHES Subject Prefix - Indicated Environment
        required: true
        type: string

      ### Usually a bad idea / not recommended
      timeout-minutes:
        description: 'Timeout minutes'
        default: 15
        required: false
        type: number
      values:
        description: 'Values file'
        default: 'values.dev.yaml'
        required: false
        type: string
    outputs:
      tag:
        description: 'Which tag was used for deployment?'
        value: ${{ jobs.deploy.outputs.tag }}
      triggered:
        description: 'Has a deployment has been triggered?'
        value: ${{ jobs.deploy.outputs.triggered }}
    secrets:
      oc_namespace:
        description: OpenShift namespace
        required: true
      oc_token:
        description: OpenShift token
        required: true
      airflow_fernet_key:
        description: Airflow Fernet Key
        required: true
      airflow_flowworks_password:
        description: Airflow Flowworks Password
        required: true
      airflow_flowworks_username:
        description: Airflow Flowworks Username
        required: true
      airflow_api_secret_key:
        description: Airflow API Secret Key
        required: true
      airflow_api_jwt_key:
        description: Airflow API JWT Key
        required: true
      airflow_sendgrid_api_key:
        description: Airflow Sendgrid API Key
        required: true
      ches_client_id:
        description: CHES Client ID
        required: true
      ches_client_secret:
        description: CHES Client Secret
        required: true

permissions: {}

jobs:
  deploy:
    name: Stack
    environment: ${{ inputs.environment }}
    runs-on: ubuntu-24.04
    outputs:
      tag: ${{ inputs.tag }}
      triggered: ${{ steps.deploy.outputs.triggered }}
    steps:
      - id: vars
        run: |
          # Vars: tag and release

          # Tag defaults to PR number, but can be overridden by inputs.tag
          tag=${{ inputs.tag }}

          # Release name includes run numbers to ensure uniqueness
          release=${{ github.event.repository.name }}-airflow-${{ inputs.environment || inputs.tag }}

          # version, to support helm packaging for non-pr based releases (workflow_dispatch). default to 1.0.0+github run number
          version=1.0.0+${{ github.run_number }}

            # Summary
          echo "tag=${tag}"
          echo "release=${release}"
          echo "version=${version}"

          # Output
          echo "tag=${tag}" >> $GITHUB_OUTPUT
          echo "release=${release}" >> $GITHUB_OUTPUT
          echo "version=${version}" >> $GITHUB_OUTPUT

      - uses: actions/checkout@v4.0.0

      - name: Helm Deploy
        id: deploy
        uses: bcgov/action-oc-runner@v1.2.2
        with:
          oc_namespace: ${{ secrets.OC_NAMESPACE }}
          oc_token: ${{ secrets.OC_TOKEN }}
          oc_server: ${{ vars.oc_server }}
          triggers: ${{ inputs.triggers }}
          ref: ${{ github.ref }}
          commands: |
            # Deploy
            [ -z "${{ inputs.directory }}" ] || cd "${{ inputs.directory }}"

            # Add & update repo (do it in the same shell that runs helm upgrade)
            helm repo add apache-airflow https://airflow.apache.org
            helm repo update

            # Helm upgrade/rollout (release name = airflow)
            helm upgrade --install airflow apache-airflow/airflow --version 1.18.0 \
              --wait \
              ${{ inputs.atomic && '--atomic' || '' }} \
              --timeout ${{ inputs['timeout-minutes'] }}m \
              --values "${{ inputs.values }}" \
              --set-string images.airflow.tag="${{ steps.vars.outputs.tag }}" \
              --set-string secrets.bcwatFlowworks.password="${{ secrets.airflow_flowworks_password }}" \
              --set-string secrets.bcwatFlowworks.username="${{ secrets.airflow_flowworks_username }}" \
              --set-string secrets.fernet.key="${{ secrets.airflow_fernet_key }}" \
              --set-string secrets.api.secretKey="${{ secrets.airflow_api_secret_key }}" \
              --set-string secrets.api.jwtKey="${{ secrets.airflow_api_jwt_key }}" \
              --set-string secrets.ches.apiUrl="${{ inputs.ches_api_url }}" \
              --set-string secrets.ches.loginUrl="${{ inputs.ches_login_url }}" \
              --set-string secrets.ches.clientId="${{ secrets.ches_client_id }}" \
              --set-string secrets.ches.clientSecret="${{ secrets.ches_client_secret }}" \
              --set-string secrets.ches.fromAddress="${{ inputs.ches_from }}" \
              --set-string secrets.ches.toAddress="${{ inputs.ches_to }}" \
              --set-string secrets.ches.subjectPrefix="${{ inputs.ches_subject_prefix }}" \
              --set-string "apiServer.extraInitContainers[0].image=ghcr.io/bcgov/nr-bcwat/migrations:${{ steps.vars.outputs.tag }}" \
              --set-string "apiServer.extraInitContainers[0].env[0].valueFrom.secretKeyRef.name=${{ inputs.db_name }}-crunchy-pguser-${{ inputs.db_user }}" \
              --set-string "apiServer.extraInitContainers[0].env[1].valueFrom.secretKeyRef.name=${{ inputs.db_name }}-crunchy-pguser-${{ inputs.db_user }}" \
              --set-string "apiServer.extraInitContainers[0].env[2].valueFrom.secretKeyRef.name=${{ inputs.db_name }}-crunchy-pguser-${{ inputs.db_user }}" \
              --set-string apiServer.podAnnotations."rollout-timestamp"="$(date +%s)" \
              --set-string scheduler.podAnnotations."rollout-timestamp"="$(date +%s)" \
              --set-string triggerer.podAnnotations."rollout-timestamp"="$(date +%s)" \
              --set-string dagProcessor.podAnnotations."rollout-timestamp"="$(date +%s)" \
              --debug 2>&1

            # Helm release history (match the release name used above)
            helm history airflow

            # Completed pod cleanup
            oc delete po --field-selector=status.phase==Succeeded || true
