name: "Build & Push Restore from S3"

on:
  push:
    # branches:
    #   - database-backup
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
    builds:
        name: Build Matrix
        permissions:
          packages: write
        runs-on: ubuntu-24.04
        strategy:
          matrix:
            package: [backup_and_restore_database/restore_database]
        timeout-minutes: 10
        steps:
          - uses: bcgov/action-builder-ghcr@v3.0.1
            with:
              keep_versions: 50
              package: ${{ matrix.package }}
              tags: |
                latest
              tag_fallback: latest
              diff_branch: dev
