name: Manual Build & Push - Airflow BCGov Openshift

on:
  workflow_dispatch:

permissions: {}

jobs:
  builds:
    name: Build Matrix
    permissions:
      packages: write
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        package: [airflow]
    timeout-minutes: 10
    steps:
      - uses: bcgov/action-builder-ghcr@v3.0.1
        with:
          keep_versions: 50
          package: ${{ matrix.package }}
          tags: latest
          tag_fallback: latest
          triggers: ('${{ matrix.package }}/')
          diff_branch: dev
