name: Dev PR Open - Unit Tests

on:
  pull_request:
    branches: [dev]

permissions: {}

jobs:
  unit_tests:
    uses: ./.github/workflows/.unit-tests.yml
    secrets:
      mapbox_token: ${{ secrets.MAPBOX_TOKEN }}
