name: "DISASTER RECOVERY - Test: Deploy & Seed Database"

on:
  workflow_dispatch:
    inputs:
      SEED_DB:
        description: 'Seed the database after deployment'
        required: true
        default: false
        type: boolean

concurrency:
  # Do not interrupt previous workflows
  group: ${{ github.workflow }}
  cancel-in-progress: false

permissions: {}

jobs:
    deploys:
        name: Deploys Latest
        uses: ./.github/workflows/.db-deployer.yml
        secrets: inherit
        with:
            environment: test
            directory: ./charts/openshift/crunchy
            name: bcwat-test
            values: values.test.yaml
            timeout-minutes: 30
            seed_db: ${{ inputs.SEED_DB }}
