name: "Foundry OKD: Update Client/App Images & Deploy Helm Release"

on:
  push:
    branches:
      - NR-BCWAT-40/cicd
    # paths:
    #   - client/**
    #   - backend/**
    #   - charts/app/**
  workflow_dispatch:

jobs:
  deploy_application:
    runs-on: ubuntu-latest
    steps:
      # Connect to OnPrem WG
      - name: Set up WireGuard Connection
        uses: niklaskeerl/easy-wireguard-action@v2
        with:
          WG_CONFIG_FILE: ${{ secrets.FOUNDRY_ONPREM_WG_CONF }}
      # Install OC CLI
      - name: Install oc CLI
        run: |
          curl -LO https://mirror.openshift.com/pub/openshift-v4/clients/ocp/latest/openshift-client-linux.tar.gz
          tar -xvf openshift-client-linux.tar.gz oc
          sudo mv oc /usr/local/bin
      # Utilize
      - name: BC Gov OC Runner
        id: deploy
        uses: bcgov/action-oc-runner@13d14b8f41df24226036385510472f683350850b # v1.0.0
        with:
          oc_namespace: bcwat
          oc_token: ${{ secrets.FOUNDRY_OKD_TOKEN }}
          oc_server: ${{ secrets.OKD_SERVER }}
