name: "Foundry OKD: Test Clone DB From S3"

on:
  push:
    branches:
      - 453-db-creation-gha
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  create_database:
    runs-on: ubuntu-latest
    steps:
      # Connect to OnPrem WG
      - name: Checkout
        uses: actions/checkout@v4

      # Connect to OnPrem WG
      - name: Set up WireGuard Connection
        uses: niklaskeerl/easy-wireguard-action@v2
        with:
          WG_CONFIG_FILE: ${{ secrets.FOUNDRY_ONPREM_WG_CONF }}

      # Install OC CLI - Despite OC Login Action specifying OC is installed
      # for Ubuntu Runners, this fails without the install:
      # --------------------------------
      # Run redhat-actions/oc-login@v1
      # Authenticating using token
      # Error: Error: Unable to locate executable file: oc. Please verify either the file path exists or the file can be found within a directory specified by the PATH environment variable. Also check the file mode to verify the file is executable.
      # -------------
      - name: Install oc CLI
        run: |
          curl -LO https://mirror.openshift.com/pub/openshift-v4/clients/ocp/latest/openshift-client-linux.tar.gz
          tar -xvf openshift-client-linux.tar.gz oc
          sudo mv oc /usr/local/bin

      - name: Install Helm CLI
        run: |
          curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

      # This is for onPrem only
      # BC Gov Actions will use the OC Runner Action:
      # bcgov/action-oc-runner@5882b707c20135424f62202f80d56c1d243fd96c
      - name: Authenticate to OKD and set context
        uses: redhat-actions/oc-login@v1
        with:
          openshift_server_url: ${{ secrets.OKD_SERVER }}
          openshift_token: ${{ secrets.FOUNDRY_OKD_TOKEN }}
          insecure_skip_tls_verify: true
          namespace: bcwat

      - name: Helm Upgrade Application
        working-directory: ./charts/okd-clone/crunchy
        run: |
          helm upgrade --install bcwat-db . \
            --namespace bcwat-clone \
            -f values.yaml \
            --set crunchy.pgBackRest.s3.accessKey=${{ secrets.S3_ACCESS_KEY }} \
            --set crunchy.pgBackRest.s3.secretKey=${{ secrets.S3_SECRET_KEY }} \
            --set crunchy.pgBackRest.s3.bucketName=${{ secrets.S3_BUCKET_NAME }} \
            --set crunchy.pgBackRest.s3.endpointUrl=${{ secrets.S3_ENDPOINT_URL }} \
            --timeout 15m
