name: PR

on:
  push:
    branches:
      - 115-bcgov-cicd

# concurrency:
#   # Cancel in progress for PR open and close
#   group: ${{ github.event.number }}
#   cancel-in-progress: true

permissions: {}

jobs:
  # https://github.com/bcgov/action-builder-ghcr
  builds_client_with_args:
    name: Builds Client
    permissions:
      packages: write
    runs-on: ubuntu-24.04
    timeout-minutes: 10
    steps:
      - uses: bcgov/action-builder-ghcr@ace71f7a527ca6fc43c15c7806314be5a4579d2c # v2.3.0
        with:
          keep_versions: 50
          package: client
          tag: 1.0.1
          # tag: ${{ github.event.number }}
          tag_fallback: latest
          triggers: ('client/')
          build_args: |
            VITE_APP_MAPBOX_TOKEN=${{ secrets.FOUNDRY_MAPBOX_TOKEN }}
            VITE_BASE_API_URL=https://nr-bcwat-dev.apps.silver.devops.gov.bc.ca/api
          diff_branch: dev

  builds_remaining_packages:
    name: Builds Remaining Packages
    permissions:
      packages: write
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        package: [backend]
    timeout-minutes: 10
    steps:
      - uses: bcgov/action-builder-ghcr@ace71f7a527ca6fc43c15c7806314be5a4579d2c # v2.3.0
        with:
          keep_versions: 50
          package: ${{ matrix.package }}
          tag: 1.0.1
          # tag: ${{ github.event.number }}
          tag_fallback: latest
          triggers: ('${{ matrix.package }}/')
          diff_branch: dev

  # https://github.com/bcgov/quickstart-openshift-helpers
  deploys:
    name: Deploys Latest
    # name: Deploys (${{ github.event.number }})
    needs: [builds_client_with_args, builds_remaining_packages]
    uses: ./.github/workflows/.deployer.yml
    secrets:
      oc_namespace: ${{ secrets.OC_NAMESPACE }}
      oc_token: ${{ secrets.OC_TOKEN }}
    with:
      # db_user: app-${{ github.event.number }}
      tag: 1.0.1
      db_user: app-latest
      params: --set global.secrets.persist=false
      triggers: ('backend/' 'client/' 'charts/app')
      directory: ./charts/app
      values: values.dev.yaml

  # tests:
  #    name: Tests
  #    if: needs.deploys.outputs.triggered == 'true'
  #    needs: [deploys]
  #    uses: ./.github/workflows/.tests.yml

  results:
    name: PR Results
    needs: [builds_client_with_args, builds_remaining_packages]
    if: always()
    runs-on: ubuntu-24.04
    steps:
      - if: contains(needs.*.result, 'failure')||contains(needs.*.result, 'canceled')
        run: echo "At least one job has failed." && exit 1
      - run: echo "Success!"
