name: PR

on:
  pull_request:
    branches: [main]

concurrency:
  # Cancel in progress for PR open and close
  group: ${{ github.event.number }}
  cancel-in-progress: true

permissions: {}

jobs:
  # unit_tests:
  #   uses: ./.github/workflows/.unit-tests.yml
  #   secrets:
  #     mapbox_token: ${{ secrets.FOUNDRY_MAPBOX_TOKEN }}
  builds:
    name: Build Matrix
    # needs: [unit_tests]
    permissions:
      packages: write
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        package: [backend, client, migrations]
    timeout-minutes: 10
    steps:
      - uses: bcgov/action-builder-ghcr@v3.0.1
        with:
          keep_versions: 50
          package: ${{ matrix.package }}
          tags: |
            ${{ github.event.number }}
            latest
          tag_fallback: latest
          triggers: ('${{ matrix.package }}/')
          diff_branch: dev

  # https://github.com/bcgov/quickstart-openshift-helpers
  deploys:
    name: Deploys Latest
    # name: Deploys (${{ github.event.number }})
    needs: [builds]
    uses: ./.github/workflows/.deployer.yml
    secrets:
      oc_namespace: ${{ secrets.OC_NAMESPACE }}
      oc_token: ${{ secrets.OC_TOKEN }}
      mapbox_token: ${{ secrets.FOUNDRY_MAPBOX_TOKEN }}
    with:
      db_user: bcwat-api-admin
      db_name: bcwat-dev
      triggers: ('backend/' 'client/' 'migrations/' 'charts/openshift/app' 'charts/openshift/crunchy')
      directory: ./charts/openshift/app
      values: values.yaml

  system_tests:
    name: Tests
    if: needs.deploys.outputs.triggered == 'true'
    needs: [deploys]
    uses: ./.github/workflows/.system-tests.yml

  results:
    name: PR Results
    needs: [builds, deploys, system_tests]
    if: always()
    runs-on: ubuntu-24.04
    steps:
      - if: contains(needs.*.result, 'failure')||contains(needs.*.result, 'canceled')
        run: echo "At least one job has failed." && exit 1
      - run: echo "Success!"
