name: Prod Deploy

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Image tag set to deploy; e.g. PR number or prod"
        type: string
        default: 'prod'

concurrency:
  # Do not interrupt previous workflows
  group: ${{ github.workflow }}
  cancel-in-progress: false

jobs:
  deploy-prod-airflow:
    name: Deploy Airflow (PROD)
    uses: ./.github/workflows/.airflow-deployer.yml
    permissions:
      packages: write
    secrets: inherit
    with:
      tag: ${{ inputs.tag }}
      environment: prod
      directory: ./charts/openshift/airflow
      values: values.prod.yaml
      timeout-minutes: 15
  deploy-prod:
    name: Deploy (PROD)
    uses: ./.github/workflows/.deployer.yml
    permissions:
      packages: write
    secrets: inherit
    with:
      environment: PROD
      db_user: app
      params:
        --set backend.deploymentStrategy=RollingUpdate
        --set frontend.deploymentStrategy=RollingUpdate
        --set global.autoscaling=true
        --set frontend.pdb.enabled=true
        --set backend.pdb.enabled=true
      tag: ${{ inputs.tag }}

  promote:
    name: Promote Images
    needs: [deploy-prod]
    runs-on: ubuntu-24.04
    permissions:
      packages: write
    strategy:
      matrix:
        package: [migrations, backend, client]
    timeout-minutes: 1
    steps:
      - uses: shrink/actions-docker-registry-tag@v4 # v4
        with:
          registry: ghcr.io
          repository: ${{ github.repository }}/${{ matrix.package }}
          target: ${{ needs.deploy-prod.outputs.tag }}
          tags: prod
