name: Prod Deploy

on:
  workflow_dispatch:

concurrency:
  # Do not interrupt previous workflows
  group: ${{ github.workflow }}
  cancel-in-progress: false

jobs:
  builds:
    name: Build Matrix
    permissions:
      packages: write
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        package: [backend, client, pdf-generator]
    timeout-minutes: 10
    steps:
      - uses: bcgov/action-builder-ghcr@v3.0.1
        with:
          keep_versions: 50
          package: ${{ matrix.package }}
          tags: prod
          build_args:
            CLIENT_URL=https://nr-bcwat.bcwatertool.ca
            # TODO - Update if URL changes
  deploy-prod:
    name: Deploy (PROD)
    needs: [builds]
    uses: ./.github/workflows/.deployer.yml
    permissions:
      packages: write
    secrets: inherit
    with:
      environment: prod
      directory: ./charts/openshift/app
      db_user: bcwat-api-read-only
      db_name: bcwat-prod
      values: values.prod.yaml
      timeout-minutes: 15
      tag: prod
      client_url: https://nr-bcwat.bcwatertool.ca

  build-airflow:
    name: Build Matrix
    permissions:
      packages: write
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        package: [airflow, migrations]
    timeout-minutes: 10
    steps:
      - uses: bcgov/action-builder-ghcr@v3.0.1
        with:
          keep_versions: 50
          package: ${{ matrix.package }}
          tags: prod

  resolve-prod-vars:
    name: Resolve Prod Variables
    runs-on: ubuntu-latest
    environment: prod
    outputs:
      ches_api_url: ${{ vars.CHES_API_URL }}
      ches_login_url: ${{ vars.CHES_LOGIN_URL }}
      ches_from: ${{ vars.CHES_FROM }}
      ches_to: ${{ vars.CHES_TO }}
      ches_subject_prefix: ${{ vars.CHES_SUBJECT_PREFIX }}
    steps:
      - run: echo "Fetch PROD Environment Variables..."
  deploy-prod-airflow:
    name: Deploy Airflow (PROD)
    needs: [build-airflow, resolve-prod-vars]
    uses: ./.github/workflows/.airflow-deployer.yml
    permissions:
      packages: write
    secrets: inherit
    with:
      tag: prod
      environment: prod
      directory: ./charts/openshift/airflow
      values: values.prod.yaml
      db_user: bcwat-api-admin
      db_name: bcwat-prod
      ches_api_url: ${{ needs.resolve-prod-vars.ches_api_url }}
      ches_login_url: ${{ needs.resolve-prod-vars.ches_login_url }}
      ches_from: ${{ needs.resolve-prod-vars.ches_from }}
      ches_to: ${{ needs.resolve-prod-vars.ches_to }}
      ches_subject_prefix: ${{ needs.resolve-prod-vars.ches_subject_prefix }}
      timeout-minutes: 45
