name: Prod Deploy

on:
  workflow_dispatch:

concurrency:
  # Do not interrupt previous workflows
  group: ${{ github.workflow }}
  cancel-in-progress: false

jobs:
  builds:
    name: Build Matrix
    permissions:
      packages: write
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        package: [backend, client, migrations]
    timeout-minutes: 10
    steps:
      - uses: bcgov/action-builder-ghcr@v3.0.1
        with:
          keep_versions: 50
          package: ${{ matrix.package }}
          tags: prod
          build_args:
            CLIENT_URL=https://${{ github.event.repository.name }}-prod-frontend.apps.silver.devops.gov.bc.ca

  deploy-prod-airflow:
    name: Deploy Airflow (PROD)
    uses: ./.github/workflows/.airflow-deployer.yml
    permissions:
      packages: write
    secrets: inherit
    with:
      tag: latest
      environment: prod
      directory: ./charts/openshift/airflow
      values: values.prod.yaml
      timeout-minutes: 15

  deploy-prod:
    name: Deploy (PROD)
    needs: [builds]
    uses: ./.github/workflows/.deployer.yml
    permissions:
      packages: write
    secrets: inherit
    with:
      environment: prod
      directory: ./charts/openshift/app
      db_user: bcwat-api-read-only
      db_name: bcwat-prod
      values: values.test.yaml
      timeout-minutes: 45
      tag: prod
